// Generated by KERN — DO NOT EDIT MANUALLY
// Regenerate with: kern sync --mode

export const mode = {
  radius: {
    "none": "rounded-none",
    "xs": "rounded-[var(--radius-xs)]",
    "sm": "rounded-[var(--radius-sm)]",
    "md": "rounded-[var(--radius-md)]",
    "lg": "rounded-[var(--radius-lg)]",
    "xl": "rounded-[var(--radius-xl)]",
    "full": "rounded-full",
  },

  color: {
    bg: {
      base: "bg-background",
      card: "bg-card",
      muted: "bg-muted",
      primary: "bg-primary",
      secondary: "bg-secondary",
      accent: "bg-accent",
      popover: "bg-popover",
      destructive: "bg-destructive",
      success: "bg-success",
      warning: "bg-warning",
      info: "bg-info",
    },
    text: {
      base: "text-foreground",
      card: "text-card-foreground",
      muted: "text-muted-foreground",
      primary: "text-primary-foreground",
      "primary-container": "text-primary-container-foreground",
      secondary: "text-secondary-foreground",
      "secondary-container": "text-secondary-container-foreground",
      tertiary: "text-tertiary-foreground",
      "tertiary-container": "text-tertiary-container-foreground",
      accent: "text-accent-foreground",
      popover: "text-popover-foreground",
      destructive: "text-destructive-foreground",
      surface: "text-surface-foreground",
      "surface-variant": "text-surface-variant-foreground",
    },
    border: {
      default: "border-border",
      input: "border-input",
      ring: "border-ring",
    },
  },

  typography: {
    display: {
      lg: "text-[57px] leading-[64px] font-normal",
      md: "text-[45px] leading-[52px] font-normal",
      sm: "text-[36px] leading-[44px] font-normal",
    },
    headline: {
      lg: "text-[32px] leading-[40px] font-normal",
      md: "text-[28px] leading-[36px] font-normal",
      sm: "text-[24px] leading-[32px] font-normal",
    },
    title: {
      lg: "text-[22px] leading-[28px] font-normal",
      md: "text-[16px] leading-[24px] font-medium",
      sm: "text-[14px] leading-[20px] font-medium",
    },
    body: {
      lg: "text-[16px] leading-[24px] font-normal",
      md: "text-[14px] leading-[20px] font-normal",
      sm: "text-[12px] leading-[16px] font-normal",
    },
    label: {
      lg: "text-[14px] leading-[20px] font-medium",
      md: "text-[12px] leading-[16px] font-medium",
      sm: "text-[11px] leading-[16px] font-medium",
    },
  },

  spacing: {
    "0": "0",
    "1": "var(--grid-1)",
    "2": "var(--grid-2)",
    "3": "var(--grid-3)",
    "4": "var(--grid-4)",
    "6": "var(--grid-6)",
    "8": "var(--grid-8)",
    "12": "var(--grid-12)",
    "16": "var(--grid-16)",
  },

  elevation: {
    none: "shadow-none",
    sm: "shadow-sm",
    md: "shadow-md",
    lg: "shadow-lg",
  },
} as const

export type Mode = typeof mode
