// Generated by KERN — DO NOT EDIT MANUALLY
// Regenerate with: kern sync --mode

export const mode = {
  radius: "rounded-none",

  color: {
    bg: {
      base: "bg-background",
      card: "bg-card",
      muted: "bg-muted",
      primary: "bg-primary",
      secondary: "bg-secondary",
      accent: "bg-accent",
      popover: "bg-popover",
      destructive: "bg-destructive",
      success: "bg-success",
      warning: "bg-warning",
      info: "bg-info",
    },
    text: {
      base: "text-foreground",
      card: "text-card-foreground",
      muted: "text-muted-foreground",
      primary: "text-primary-foreground",
      secondary: "text-secondary-foreground",
      accent: "text-accent-foreground",
      popover: "text-popover-foreground",
      destructive: "text-destructive-foreground",
    },
    border: {
      default: "border-border",
      input: "border-input",
      ring: "border-ring",
    },
  },

  typography: {
    display: {
      lg: "text-[48px] leading-[48px] font-black uppercase",
      md: "text-[32px] leading-[32px] font-extrabold uppercase",
    },
    headline: {
      lg: "text-[24px] leading-[32px] font-bold uppercase",
      md: "text-[20px] leading-[32px] font-bold uppercase",
    },
    body: {
      lg: "text-[15px] leading-[24px] font-normal",
      md: "text-[13px] leading-[16px] font-normal",
    },
    label: {
      md: "text-[10px] leading-[16px] font-bold uppercase tracking-[0.1em]",
    },
    caption: {
      caption: "text-[11px] leading-[16px] font-normal",
    },
  },

  spacing: {
    "0": "0",
    "1": "var(--grid-1)",
    "2": "var(--grid-2)",
    "3": "var(--grid-3)",
    "4": "var(--grid-4)",
    "6": "var(--grid-6)",
    "8": "var(--grid-8)",
    "12": "var(--grid-12)",
    "16": "var(--grid-16)",
  },

  elevation: {
    none: "shadow-none",
    sm: "shadow-sm",
    md: "shadow-md",
    lg: "shadow-lg",
  },
} as const

export type Mode = typeof mode
