/**
 * Existing Context Scanner Plugin
 */

import { basename } from "path";
import type { ExistingContext } from "../types.js";
import type { ScannerPlugin, ScannerContext } from "../engine/types.js";

export class ExistingContextScanner implements ScannerPlugin<ExistingContext> {
  name = "existingContext";
  filePatterns = ["**/*.md", "**/.cursorrules", "**/.windsurfrules", "**/.clinerules", "**/.cursor/rules/*.mdc"];
  
  private context: ExistingContext = {
    hasClaudeMd: false,
    hasAgentsMd: false,
    hasAiFolder: false,
    aiFiles: [],
    hasCursorRules: false,
    hasWindsurfRules: false,
    hasClineRules: false,
    hasGeminiMd: false,
    hasCopilotInstructions: false,
    hasCursorMdc: false,
    cursorMdcFiles: [],
    allRules: [],
  };

  async onFile(path: string, content: string) {
    const fileName = basename(path);

    if (fileName.toLowerCase() === "claude.md") {
      this.context.hasClaudeMd = true;
      this.context.claudeMdPath = path;
      this.context.claudeMdContent = content;
    } else if (fileName.toLowerCase() === "agents.md") {
      if (!content.includes("Auto-generated by [hashmark]") && !content.includes("Auto-generated by [agentsmith]")) {
        this.context.hasAgentsMd = true;
        this.context.agentsMdPath = path;
      }
    } else if (path.includes(".ai/") && path.endsWith(".md")) {
      this.context.hasAiFolder = true;
      this.context.aiFiles.push(path);
    } else if (fileName === ".cursorrules") {
      this.context.hasCursorRules = true;
      this.context.cursorRulesContent = content;
    } else if (fileName === ".windsurfrules") {
      this.context.hasWindsurfRules = true;
      this.context.windsurfRulesContent = content;
    } else if (fileName === ".clinerules") {
      this.context.hasClineRules = true;
      this.context.clineRulesContent = content;
    } else if (fileName.toLowerCase() === "gemini.md") {
      this.context.hasGeminiMd = true;
      this.context.geminiMdContent = content;
    } else if (path.endsWith("copilot-instructions.md")) {
      this.context.hasCopilotInstructions = true;
      this.context.copilotInstructionsContent = content;
    } else if (path.includes(".cursor/rules/") && path.endsWith(".mdc")) {
      this.context.hasCursorMdc = true;
      this.context.cursorMdcFiles.push(path);
      if (!this.context.cursorMdcContent) this.context.cursorMdcContent = {};
      this.context.cursorMdcContent[path] = content;
    }
  }

  finalize() {
    this.context.allRules = mergeAllRules(this.context);
  }

  getResult() {
    return this.context;
  }
}

/** 
 * Extracts rules from any markdown or plain text content
 */
export function extractRulesFromContent(content: string): string[] {
  const rules: string[] = [];
  const lines = content.split("\n");
  let inRulesSection = false;

  for (const line of lines) {
    if (line.match(/^#+\s*(Rules|Critical|Important|Guidelines|Conventions|Standards|Instructions|Preferences)/i)) {
      inRulesSection = true;
      continue;
    }
    if (inRulesSection && line.match(/^#+\s/)) inRulesSection = false;

    if (inRulesSection) {
      const ruleMatch = line.match(/^[\d\-\*]+\.?\s*\*?\*?(.+)\*?\*?/);
      if (ruleMatch && ruleMatch[1].trim().length > 10) {
        rules.push(ruleMatch[1].trim().replace(/\*\*/g, ""));
      }
    }

    if (line.includes("NEVER") || line.includes("ALWAYS") || line.includes("MUST")) {
      const cleanLine = line.replace(/^[\s\-\*\d\.]+/, "").trim();
      if (cleanLine.length > 20 && !rules.includes(cleanLine)) rules.push(cleanLine);
    }
  }
  return rules;
}

function extractRulesFromMdc(content: string): string[] {
  const mdcBody = content.replace(/^---[\s\S]*?---\s*\n?/, "");
  return extractRulesFromContent(mdcBody);
}

function mergeAllRules(context: ExistingContext): string[] {
  const allRules: string[] = [];
  if (context.claudeMdContent) allRules.push(...extractRulesFromContent(context.claudeMdContent));
  if (context.cursorRulesContent) allRules.push(...extractRulesFromContent(context.cursorRulesContent));
  if (context.windsurfRulesContent) allRules.push(...extractRulesFromContent(context.windsurfRulesContent));
  if (context.clineRulesContent) allRules.push(...extractRulesFromContent(context.clineRulesContent));
  if (context.geminiMdContent) allRules.push(...extractRulesFromContent(context.geminiMdContent));
  if (context.copilotInstructionsContent) allRules.push(...extractRulesFromContent(context.copilotInstructionsContent));
  if (context.cursorMdcContent) {
    for (const content of Object.values(context.cursorMdcContent)) allRules.push(...extractRulesFromMdc(content));
  }

  const seen = new Set<string>();
  return allRules.filter(rule => {
    const key = rule.toLowerCase().trim();
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

/** Legacy support */
export async function scanExistingContext(dir: string): Promise<ExistingContext> {
  const { ScannerRegistry } = await import("../engine/registry.js");
  const { CodebaseVisitor } = await import("../engine/visitor.js");
  const registry = new ScannerRegistry().register(new ExistingContextScanner());
  const visitor = new CodebaseVisitor(registry);
  const result = await visitor.visit(dir);
  return result.pluginResults.existingContext;
}
