import { existsSync, readFileSync } from "fs";
import { join } from "path";

export interface ExistingContext {
  source: string;
  format: "claude-md" | "agents-md" | "unknown";
  sections: Map<string, string>;
  raw: string;
}

/**
 * Detect and load an existing context file from the project.
 * Checks: CLAUDE.md, .claude/CLAUDE.md, AGENTS.md, .github/AGENTS.md
 */
export function loadExistingContext(projectDir: string): ExistingContext | null {
  const candidates = [
    { path: "CLAUDE.md", format: "claude-md" as const },
    { path: ".claude/CLAUDE.md", format: "claude-md" as const },
    { path: "AGENTS.md", format: "agents-md" as const },
    { path: ".github/AGENTS.md", format: "agents-md" as const },
  ];

  for (const { path, format } of candidates) {
    const full = join(projectDir, path);
    if (existsSync(full)) {
      const raw = readFileSync(full, "utf-8");
      if (raw.includes("Auto-generated by hashmark") || raw.includes("Generated by hashmark")) continue;
      const sections = parseSections(raw);
      return { source: path, format, sections, raw };
    }
  }
  return null;
}

function parseSections(content: string): Map<string, string> {
  const sections = new Map<string, string>();
  const parts = content.split(/\n(?=## )/);
  for (const part of parts) {
    const headerMatch = part.match(/^## (.+)/);
    if (headerMatch) {
      sections.set(headerMatch[1].trim(), part.trim());
    } else if (part.trim()) {
      sections.set("_preamble", part.trim());
    }
  }
  return sections;
}

/**
 * Merge human-authored context sections into the generated output.
 * Human-only sections are appended as a "Human Notes" block.
 */
export function mergeContexts(generated: string, existing: ExistingContext): string {
  const generatedSections = parseSections(generated);

  const knownGeneratedNames = new Set(
    [...generatedSections.keys()].map(k => k.toLowerCase())
  );

  const humanOnly: string[] = [];
  for (const [name, content] of existing.sections) {
    if (name === "_preamble") continue;
    const isKnown =
      knownGeneratedNames.has(name.toLowerCase()) ||
      ["identity", "orientation", "operations", "constraints", "knowledge", "build health"].includes(
        name.toLowerCase()
      );
    if (!isKnown) {
      humanOnly.push(content);
    }
  }

  if (humanOnly.length === 0) return generated;

  return (
    generated +
    `\n\n## Human Notes\n\n> Preserved from \`${existing.source}\`\n\n` +
    humanOnly.join("\n\n")
  );
}
