import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("Seeding database...");

  // Create a demo user (useful for local dev / staging)
  const user = await prisma.user.upsert({
    where: { email: "demo@hashmark.md" },
    update: {},
    create: {
      email: "demo@hashmark.md",
      name: "Demo User",
      plan: "PRO",
    },
  });

  console.log(`  User: ${user.email} (${user.plan})`);

  // Create a sample repository
  const repo = await prisma.repository.upsert({
    where: { githubRepoId: 999999999 },
    update: {},
    create: {
      userId: user.id,
      githubRepoId: 999999999,
      name: "demo-app",
      fullName: "hashmark-dev/demo-app",
      defaultBranch: "main",
      private: false,
      language: "TypeScript",
      description: "Demo repository for Hashmark",
    },
  });

  console.log(`  Repo: ${repo.fullName}`);

  // Create a completed scan with sample stats
  const scan = await prisma.scan.create({
    data: {
      repositoryId: repo.id,
      status: "COMPLETED",
      fileCount: 47,
      lineCount: 3820,
      componentCount: 12,
      apiRouteCount: 6,
      modelCount: 4,
      tokenEstimate: 8500,
      duration: 4200,
    },
  });

  console.log(`  Scan: ${scan.id} (${scan.status})`);

  // Create sample generated files for all 8 formats
  const formats = [
    { format: "AGENTS_MD", fileName: "AGENTS.md", tokens: 4200 },
    { format: "CLAUDE_MD", fileName: "CLAUDE.md", tokens: 2100 },
    { format: "CURSORRULES", fileName: ".cursorrules", tokens: 1800 },
    { format: "CURSOR_MDC", fileName: ".cursor/rules/hashmark.mdc", tokens: 1900 },
    { format: "COPILOT_INSTRUCTIONS", fileName: ".github/copilot-instructions.md", tokens: 1600 },
    { format: "WINDSURFRULES", fileName: ".windsurfrules", tokens: 1700 },
    { format: "GEMINI_MD", fileName: "GEMINI.md", tokens: 2000 },
    { format: "CLINE_RULES", fileName: ".clinerules", tokens: 1500 },
  ] as const;

  for (const f of formats) {
    await prisma.generatedFile.create({
      data: {
        scanId: scan.id,
        format: f.format,
        fileName: f.fileName,
        content: `# ${f.fileName}\n\nGenerated by Hashmark (seed data)\n\nThis is sample content for the ${f.format} format.\n`,
        tokenCount: f.tokens,
      },
    });
  }

  console.log(`  Generated files: ${formats.length} formats`);

  // Create a sample custom rule
  await prisma.customRule.create({
    data: {
      userId: user.id,
      name: "Always use TypeScript strict mode",
      description: "Enforce strict TypeScript in all generated context files",
      rule: "All code examples must use TypeScript strict mode with noUncheckedIndexedAccess enabled.",
      scope: "REPO",
      enabled: true,
    },
  });

  console.log("  Custom rule: 1 created");
  console.log("Seed complete.");
}

main()
  .catch((e) => {
    console.error("Seed failed:", e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
