/**
 * Hashmark GitHub Action
 *
 * One scan. Every format. Always in sync.
 *
 * Runs the hashmark scanner engine on every push,
 * generates AI context files for every coding tool,
 * and auto-commits them back to the repo.
 */

import * as core from "@actions/core";
import * as exec from "@actions/exec";
import * as github from "@actions/github";
import { join } from "path";

async function run(): Promise<void> {
  try {
    // Read inputs
    const formats = core.getInput("formats") || "all";
    const commitMode = core.getInput("commit-mode") || "auto";
    const customCommitMessage = core.getInput("commit-message");
    const targetBranch = core.getInput("branch");
    const compact = core.getInput("compact") === "true";
    const customRules = core.getInput("custom-rules");

    const workspace = process.env.GITHUB_WORKSPACE || process.cwd();

    core.info("# hashmark — AI Context Sync");
    core.info("");

    // Step 1: Resolve CLI — bundled alongside the action dist, no npm install needed
    const cliPath = join(__dirname, "cli.js");

    // Step 2: Build args
    const args: string[] = [cliPath, workspace, "--format", formats, "--force"];
    if (compact) args.push("--compact");

    // Pass custom rules via --rules flag if provided
    if (customRules) {
      const rules = customRules.split("\n").filter(Boolean);
      for (const rule of rules) {
        args.push("--rule", rule);
      }
    }

    core.info(`Running hashmark scan (formats: ${formats})...`);
    core.info("");

    // Step 3: Run hashmark CLI via node (no global install required)
    let output = "";
    await exec.exec("node", args, {
      listeners: {
        stdout: (data: Buffer) => {
          output += data.toString();
        },
        stderr: (data: Buffer) => {
          output += data.toString();
        },
      },
    });

    // Parse output for file count
    const filesMatch = output.match(/Generated (\d+) format file/);
    const filesGenerated = filesMatch ? parseInt(filesMatch[1], 10) : 0;

    // Extract generated format names from output
    const formatLines = output.match(/✓ (.+?) \(/g) || [];
    const generatedFormats = formatLines
      .map(l => l.replace("✓ ", "").replace(" (", "").trim())
      .filter(Boolean);

    core.info("");
    core.info(`Generated ${filesGenerated} format files`);

    // Step 4: Check for changes
    let diffOutput = "";
    await exec.exec("git", ["status", "--porcelain"], {
      cwd: workspace,
      listeners: {
        stdout: (data: Buffer) => {
          diffOutput += data.toString();
        },
      },
    });

    const hasChanges = diffOutput.trim().length > 0;

    if (!hasChanges) {
      core.info("No changes detected — context files are up to date.");
      core.setOutput("files-generated", filesGenerated.toString());
      core.setOutput("formats-generated", generatedFormats.join(","));
      core.setOutput("files-changed", "false");
      return;
    }

    // Step 5: Commit changes
    const commitMessage = customCommitMessage ||
      `chore: sync AI context files [hashmark]\n\nAuto-generated by hashmark — ${filesGenerated} format files updated.\nhttps://hashmark.md`;

    // Configure git
    await exec.exec("git", ["config", "user.name", "hashmark[bot]"], { cwd: workspace });
    await exec.exec("git", ["config", "user.email", "hashmark[bot]@users.noreply.github.com"], { cwd: workspace });

    if (commitMode === "pr") {
      // PR mode: create a branch and PR
      const prBranch = `hashmark/sync-${Date.now()}`;
      await exec.exec("git", ["checkout", "-b", prBranch], { cwd: workspace });
      await exec.exec("git", ["add", "-A"], { cwd: workspace });
      await exec.exec("git", ["commit", "-m", commitMessage], { cwd: workspace });
      await exec.exec("git", ["push", "origin", prBranch], { cwd: workspace });

      // Create PR via GitHub API
      const token = process.env.GITHUB_TOKEN;
      if (token) {
        const octokit = github.getOctokit(token);
        const { owner, repo } = github.context.repo;
        const baseBranch = targetBranch || github.context.ref.replace("refs/heads/", "");

        const pr = await octokit.rest.pulls.create({
          owner,
          repo,
          title: "chore: sync AI context files [hashmark]",
          body: `## Hashmark AI Context Sync\n\nAuto-generated AI context files updated:\n\n${generatedFormats.map(f => `- ${f}`).join("\n")}\n\n---\n*Generated by [hashmark](https://hashmark.md)*`,
          head: prBranch,
          base: baseBranch,
        });

        core.info(`Created PR #${pr.data.number}: ${pr.data.html_url}`);
      }
    } else {
      // Auto mode: commit directly to current branch
      await exec.exec("git", ["add", "-A"], { cwd: workspace });
      await exec.exec("git", ["commit", "-m", commitMessage], { cwd: workspace });
      await exec.exec("git", ["push"], { cwd: workspace });
      core.info("Changes committed and pushed.");
    }

    // Set outputs
    core.setOutput("files-generated", filesGenerated.toString());
    core.setOutput("formats-generated", generatedFormats.join(","));
    core.setOutput("files-changed", "true");

    core.info("");
    core.info("Done! AI context files are now in sync.");
    core.info("https://hashmark.md");

  } catch (error) {
    if (error instanceof Error) {
      core.setFailed(error.message);
    } else {
      core.setFailed("An unexpected error occurred");
    }
  }
}

run();
