#!/usr/bin/env node
/**
 * hashmark context-inject hook
 *
 * Claude Code PreToolUse hook — injects rich file relationship context
 * (export signatures + usage mapping) when the Read tool is used.
 *
 * Generated by: hashmark hook install
 * Regenerate with: hashmark hook install
 */

import { readFileSync } from "fs";
import { dirname, join, resolve, relative } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

let input = "";
process.stdin.setEncoding("utf-8");
process.stdin.on("data", (chunk) => { input += chunk; });
process.stdin.on("end", () => {
  try {
    const event = JSON.parse(input);
    if (event.tool_name !== "Read") process.exit(0);

    const filePath = event.tool_input?.file_path;
    if (!filePath) process.exit(0);

    const indexPath = join(__dirname, "..", "index.json");
    let index;
    try {
      index = JSON.parse(readFileSync(indexPath, "utf-8"));
    } catch {
      process.exit(0);
    }

    const projectRoot = index.projectRoot || resolve(__dirname, "../..");
    const relPath = relative(projectRoot, resolve(filePath)).replace(/\\/g, "/");

    const info = index.files[relPath] || index.files[relPath.replace(/\\/g, "/")];
    if (!info) process.exit(0);

    formatAndOutput(relPath, info);
  } catch {
    process.exit(0);
  }
});

function formatAndOutput(path, info) {
  const lines = ["[hashmark context] " + path];

  // Exports with signatures — most useful for understanding what a file provides
  if (info.exports && info.exports.length > 0) {
    lines.push("");
    lines.push("Exports:");
    for (const exp of info.exports.slice(0, 12)) {
      if (typeof exp === "string") {
        lines.push("  " + exp);
      } else if (exp.signature) {
        lines.push("  " + exp.name + exp.signature);
      } else {
        lines.push("  " + exp.name + " (" + (exp.kind || "export") + ")");
      }
    }
    if (info.exports.length > 12) {
      lines.push("  ..." + (info.exports.length - 12) + " more");
    }
  }

  // Dependencies — what this file imports (compact, basename only to save tokens)
  if (info.imports && info.imports.length > 0) {
    lines.push("");
    const shown = info.imports.slice(0, 8).map(p => p.split("/").pop().replace(/\..*$/, ""));
    const suffix = info.imports.length > 8 ? " (+" + (info.imports.length - 8) + " more)" : "";
    lines.push("Depends on: " + shown.join(", ") + suffix);
  }

  // Who uses this file and WHICH exports they pull — this is the key insight
  if (info.importUsage && Object.keys(info.importUsage).length > 0) {
    lines.push("");
    const total = info.importedBy ? info.importedBy.length : Object.keys(info.importUsage).length;
    lines.push("Used by " + total + " file(s):");
    const entries = Object.entries(info.importUsage).slice(0, 10);
    for (const [importer, symbols] of entries) {
      // Show last 2 path segments so "api/repos/route" is distinct from "api/scan/route"
      const parts = importer.replace(/\..*$/, "").split("/");
      const importerName = parts.slice(-2).join("/");
      lines.push("  " + importerName + " → " + symbols.join(", "));
    }
    if (total > 10) lines.push("  ...+" + (total - 10) + " more");
  } else if (info.importedBy && info.importedBy.length > 0) {
    lines.push("");
    const shown = info.importedBy.slice(0, 6).map(p => {
      const parts = p.replace(/\..*$/, "").split("/");
      return parts.slice(-2).join("/");
    });
    const suffix = info.importedBy.length > 6 ? " (+" + (info.importedBy.length - 6) + " more)" : "";
    lines.push("Used by: " + shown.join(", ") + suffix);
  }

  // Only inject if we have something useful beyond the header
  if (lines.length <= 1) process.exit(0);

  process.stdout.write(JSON.stringify({
    hookSpecificOutput: {
      hookEventName: "PreToolUse",
      additionalContext: lines.join("\n"),
    },
  }));
  process.exit(0);
}
