/**
 * AGENTS.md Generator
 *
 * Transforms scan results into formatted documentation. Supports multiple
 * output modes:
 * - Default: Full documentation with all sections
 * - Compact: Reduced detail (~20% smaller)
 * - Compress: Signatures only (~40% smaller)
 * - Minimal: Ultra-compact (~3K tokens)
 * - XML: Structured XML format (Repomix compatible)
 *
 * @module generator
 */

import type { ScanResult, Component, Framework, Tokens, Hook, Utilities, Commands, ExistingContext, ComponentVariant, ApiRoute, ApiSchema, EnvVar, DetectedPatterns, DatabaseSchema, FileStats, BarrelExport, ComponentDependency, FileTree, ImportGraph, TypeScanResult, AntiPatternsResult, AIRecommendations, FileComplexity, FunctionComplexity } from "./types.js";
import { extractRulesFromContent } from "./scanners/existing-context.js";
import { formatFileTree } from "./scanners/file-tree.js";
import { formatImportGraph } from "./scanners/imports.js";
import { formatTypes } from "./scanners/types.js";
import { formatAntiPatterns } from "./scanners/anti-patterns.js";
import { groupComponentsByDirectory, formatDirectoryName } from "./utils/grouping.js";

/** Options for controlling AGENTS.md generation */
export interface GeneratorOptions {
  compact?: boolean;
  compress?: boolean;
  minimal?: boolean;      // Ultra-compact: TL;DR + rules + component names only (~1K tokens)
  includeTree?: boolean;  // Include file tree (always on by default now)
  xml?: boolean;          // XML format (industry standard, matches Repomix)
  existingContent?: string; // Existing file content for preserving user sections
}

/**
 * Generates AGENTS.md content from scan results
 *
 * @param result - Complete scan results from all scanners
 * @param options - Output options (compact, compress, minimal, xml)
 * @returns Formatted markdown or XML string
 *
 * @example
 * const content = generateAgentsMd(scanResult, { compact: true });
 * writeFileSync('AGENTS.md', content);
 */
export function generateAgentsMd(result: ScanResult, options: GeneratorOptions = {}): string {
  const { components, tokens, framework, hooks, utilities, commands, existingContext, variants, apiRoutes, envVars, patterns, database, stats, barrels, dependencies, fileTree, importGraph, typeExports, antiPatterns, aiRecommendations, graphqlSchemas, latentHooks } = result;
  const { compact = false, compress = false, minimal = false, includeTree = false, xml = false } = options;

  // Minimal mode: ultra-compact output (~1K tokens)
  if (minimal) {
    return generateMinimalOutput(result, options);
  }

  // XML mode: structured output (industry standard, matches Repomix)
  if (xml) {
    return generateXmlOutput(result);
  }

  const lines: string[] = [];

  // Header
  lines.push("# AGENTS.md");
  lines.push("");
  lines.push("> Auto-generated by [hashmark](https://hashmark.md)");
  lines.push("");

  // TL;DR - Quick Reference
  lines.push("## TL;DR");
  lines.push("");

  // Stack line with versions
  const stackParts: string[] = [];
  if (framework.name !== "Unknown") {
    stackParts.push(framework.version ? `${framework.name} ${framework.version}` : framework.name);
  }
  if (framework.language === "TypeScript") {
    stackParts.push(framework.versions?.typescript ? `TypeScript ${framework.versions.typescript}` : "TypeScript");
  }
  if (framework.styling) {
    stackParts.push(framework.versions?.tailwindcss ? `Tailwind ${framework.versions.tailwindcss}` : framework.styling);
  }
  if (utilities.hasShadcn) stackParts.push("shadcn/ui");
  lines.push(`- **Stack**: ${stackParts.join(" + ")}`);

  // Components
  lines.push(`- **Components**: ${components.length} total — USE EXISTING, don't create new`);

  // Key imports
  const keyImports: string[] = [];
  if (utilities.hasCn) keyImports.push(`\`cn()\` from \`${utilities.cnPath}\``);
  if (utilities.hasMode) keyImports.push(`\`mode\` from \`${utilities.modePath}\``);
  if (keyImports.length > 0) {
    lines.push(`- **Key imports**: ${keyImports.join(", ")}`);
  }

  // Hub files (most impactful)
  if (importGraph && importGraph.hubFiles.length > 0) {
    const topHubs = importGraph.hubFiles.slice(0, 4).map(h => {
      const parts = h.file.split("/");
      const filename = parts.pop()?.replace(/\.(ts|tsx|js|jsx)$/, "") || "";
      // For index files, show parent/index (e.g., "design-system/index")
      if (filename === "index" && parts.length > 0) {
        return `${parts.pop()}/${filename}`;
      }
      return filename;
    });
    lines.push(`- **High-impact files**: ${topHubs.join(", ")} (changes affect many files)`);
  }

  // Database
  if (database && database.models.length > 0) {
    lines.push(`- **Database**: ${database.provider} with ${database.models.length} models`);
  }

  // API routes
  if (apiRoutes.length > 0) {
    const protectedCount = apiRoutes.filter(r => r.isProtected).length;
    lines.push(`- **API**: ${apiRoutes.length} routes (${protectedCount} protected)`);
  }

  // Critical rules summary
  lines.push("");
  lines.push("**Rules**: Use design tokens (not hardcoded colors), use `cn()` for classes, check existing components first");
  lines.push("");

  // Getting Started Section (auto-generated setup guide)
  const gettingStarted = generateGettingStarted(result);
  if (gettingStarted) {
    lines.push(gettingStarted);
  }

  // Project Overview
  lines.push("## Project Overview");
  lines.push("");
  lines.push("| | |");
  lines.push("|---|---|");
  lines.push(`| **Framework** | ${framework.name}${framework.version ? ` ${framework.version}` : ""}${framework.router ? ` (${framework.router})` : ""} |`);
  lines.push(`| **Language** | ${framework.language} |`);
  if (framework.styling) {
    lines.push(`| **Styling** | ${framework.styling} |`);
  }
  if (utilities.hasShadcn) {
    lines.push(`| **UI Library** | shadcn/ui (${utilities.radixPackages.length} Radix packages) |`);
  }
  if (utilities.hasCn) {
    lines.push(`| **Class Utility** | \`cn()\` from \`${utilities.cnPath}\` |`);
  }
  if (utilities.hasMode) {
    lines.push(`| **Design System** | \`mode\` from \`${utilities.modePath}\` |`);
  }
  lines.push(`| **Components** | ${components.length} |`);
  if (hooks.length > 0) {
    lines.push(`| **Custom Hooks** | ${hooks.length} |`);
  }
  if (apiRoutes.length > 0) {
    lines.push(`| **API Routes** | ${apiRoutes.length} |`);
  }
  if (patterns.patterns.length > 0) {
    lines.push(`| **Patterns** | ${patterns.patterns.length} detected |`);
  }
  if (stats) {
    lines.push(`| **Codebase** | ${stats.totalFiles} files, ${stats.totalLines.toLocaleString()} lines |`);
  }
  lines.push("");

  // File Tree Section (always included for comprehensive output)
  if (fileTree) {
    lines.push(formatFileTree(fileTree));
  }

  // Critical Rules with inline examples (moved anti-patterns here for better AI parsing)
  lines.push("## Critical Rules");
  lines.push("");
  lines.push("**These rules are NON-NEGOTIABLE:**");
  lines.push("");

  // Rule 1: Use existing components
  lines.push("### 1. USE EXISTING COMPONENTS");
  lines.push(`This project has ${components.length} components. Check the list below before creating anything new.`);
  lines.push("");
  lines.push("```tsx");
  lines.push("// WRONG");
  lines.push(`<div className="rounded border p-4">...</div>`);
  lines.push("");
  lines.push("// RIGHT");
  lines.push(`<Card><CardContent>...</CardContent></Card>`);
  lines.push("```");
  lines.push("");

  // Rule 2: Use design tokens
  lines.push("### 2. USE DESIGN TOKENS");
  lines.push("Never hardcode colors. Use semantic tokens that work with theme switching.");
  lines.push("");
  lines.push("```tsx");
  lines.push("// WRONG");
  lines.push(`className="bg-blue-500 text-on-surface"`);
  lines.push(`style={{"color": "#3b82f6"}}`);
  lines.push("");
  lines.push("// RIGHT");
  lines.push(`className="bg-primary text-primary-foreground"`);
  lines.push("```");
  lines.push("");

  // Rule 3: cn() utility
  if (utilities.hasCn) {
    lines.push("### 3. USE `cn()` FOR CLASSES");
    lines.push(`Import from \`${utilities.cnPath}\`. Handles conditional classes correctly.`);
    lines.push("");
    lines.push("```tsx");
    lines.push("// WRONG");
    lines.push(`className={"btn " + (active ? "btn-active" : "")}`);
    lines.push("");
    lines.push("// RIGHT");
    lines.push(`className={cn("btn", active && "btn-active")}`);
    lines.push("```");
    lines.push("");
  }

  // Rule 4: mode design system
  if (utilities.hasMode) {
    lines.push(`### ${utilities.hasCn ? "4" : "3"}. USE \`mode\` DESIGN SYSTEM`);
    lines.push(`Import from \`${utilities.modePath}\`. Provides theme-aware styling.`);
    lines.push("");
    lines.push("```tsx");
    lines.push("// WRONG");
    lines.push(`className="rounded-lg"`);
    lines.push("");
    lines.push("// RIGHT");
    lines.push(`className={cn("...", mode.radius)}`);
    lines.push("```");
    lines.push("");
  }

  // Extract and merge rules from ALL existing context files
  if (existingContext.allRules && existingContext.allRules.length > 0) {
    const sources: string[] = [];
    if (existingContext.hasClaudeMd) sources.push("CLAUDE.md");
    if (existingContext.hasCursorRules) sources.push(".cursorrules");
    if (existingContext.hasWindsurfRules) sources.push(".windsurfrules");
    if (existingContext.hasClineRules) sources.push(".clinerules");
    if (existingContext.hasGeminiMd) sources.push("GEMINI.md");
    if (existingContext.hasCopilotInstructions) sources.push("copilot-instructions.md");
    if (existingContext.hasCursorMdc) sources.push(".cursor/rules/*.mdc");

    lines.push(`### User Rules (from ${sources.join(", ")})`);
    lines.push("");
    for (const rule of existingContext.allRules) {
      lines.push(`- ${rule}`);
    }
    lines.push("");
  }

  // Framework-specific rules
  const frameworkRules = getFrameworkRules(framework, tokens, utilities);
  if (frameworkRules.length > 0) {
    lines.push("### Framework-Specific");
    lines.push("");
    for (const rule of frameworkRules) {
      lines.push(`- ${rule}`);
    }
    lines.push("");
  }

  // Components Section
  if (components.length > 0) {
    lines.push("## Components");
    lines.push("");

    const grouped = groupComponentsByDirectory(components);
    const groupCount = Object.keys(grouped).length;

    // Cap individual component listings to keep output manageable.
    // For large codebases, show a summary table + top groups in detail.
    const MAX_LISTED_COMPONENTS = 200;
    const isLargeCodebase = components.length > MAX_LISTED_COMPONENTS;

    lines.push(`${components.length} components across ${groupCount} categories.`);
    lines.push("");

    // Sort groups: UI first, then Charts, then alphabetically
    const sortedGroups = Object.entries(grouped).sort((a, b) => {
      const aName = formatDirectoryName(a[0]);
      const bName = formatDirectoryName(b[0]);
      if (aName === "UI Components") return -1;
      if (bName === "UI Components") return 1;
      if (aName === "Charts") return -1;
      if (bName === "Charts") return 1;
      return aName.localeCompare(bName);
    });

    // For large codebases, emit a summary table first
    if (isLargeCodebase) {
      lines.push("| Category | Count |");
      lines.push("|---|---|");
      for (const [dir, comps] of sortedGroups) {
        lines.push(`| ${formatDirectoryName(dir)} | ${comps.length} |`);
      }
      lines.push("");
      lines.push(`Showing top ${MAX_LISTED_COMPONENTS} components below. Full list available in AGENTS.index.json.`);
      lines.push("");
    }

    let totalListed = 0;

    for (const [dir, comps] of sortedGroups) {
      if (isLargeCodebase && totalListed >= MAX_LISTED_COMPONENTS) break;

      const groupName = formatDirectoryName(dir);
      lines.push(`### ${groupName} (${comps.length})`);
      lines.push("");

      const compsToShow = isLargeCodebase
        ? comps.slice(0, MAX_LISTED_COMPONENTS - totalListed)
        : comps;

      for (const comp of compsToShow) {
        const allExports = comp.exports.map(e => `\`${e}\``).join(", ");
        lines.push(`- ${allExports} — \`${comp.importPath}\``);

        // Compress mode: minimal output, just component names and paths
        if (compress) {
          continue;
        }

        // In compact mode, limit props to 5 and skip descriptions
        if (!compact) {
          if (comp.props && comp.props.length > 0) {
            lines.push(`  - Props: ${comp.props.join(", ")}`);
          }
          if (comp.description) {
            lines.push(`  - ${comp.description}`);
          }
        } else if (comp.props && comp.props.length > 0) {
          const topProps = comp.props.slice(0, 5);
          const more = comp.props.length > 5 ? ` (+${comp.props.length - 5})` : "";
          lines.push(`  - Props: ${topProps.join(", ")}${more}`);
        }

        totalListed++;
      }

      if (isLargeCodebase && compsToShow.length < comps.length) {
        lines.push(`- ... ${comps.length - compsToShow.length} more in this category`);
      }
      lines.push("");
    }
  }

  // Barrel Imports Section
  if (barrels && barrels.length > 0) {
    lines.push("## Preferred Imports");
    lines.push("");
    lines.push("Use barrel imports instead of importing from individual files:");
    lines.push("");
    lines.push("```typescript");
    for (const barrel of barrels.slice(0, 5)) {
      const exampleExports = barrel.exports
        .filter(e => !e.startsWith("*"))
        .slice(0, 4)
        .join(", ");
      if (exampleExports) {
        lines.push(`import { ${exampleExports} } from "${barrel.importPath}";`);
      }
    }
    lines.push("```");
    lines.push("");
  }

  // Hooks Section
  if (hooks.length > 0) {
    lines.push("## Custom Hooks");
    lines.push("");
    for (const hook of hooks) {
      const clientNote = hook.isClientOnly ? " *(client only)*" : "";
      lines.push(`- \`${hook.name}\` — \`${hook.importPath}\`${clientNote}`);
    }
    lines.push("");
  }

  // TypeScript Types Section (skip in compact/compress mode)
  if (!compact && !compress && typeExports && (typeExports.propsTypes.length > 0 || typeExports.apiTypes.length > 0)) {
    lines.push(formatTypes(typeExports));
  }

  // Utilities Section
  if (utilities.customUtils.length > 0 || utilities.hasCn) {
    lines.push("## Utilities");
    lines.push("");
    if (utilities.hasCn) {
      lines.push(`- \`cn(...classes)\` — Class merging utility from \`${utilities.cnPath}\``);
    }
    for (const util of utilities.customUtils.slice(0, 10)) {
      lines.push(`- \`${util}()\` — from \`${utilities.cnPath}\``);
    }
    lines.push("");
  }

  // Component Dependencies Section (skip in compact mode)
  if (!compact && dependencies && dependencies.length > 0) {
    // Only show components with interesting dependencies
    const interestingDeps = dependencies.filter(
      d => d.imports.radix.length > 0 || d.imports.designSystem.length > 0
    ).slice(0, 15);

    if (interestingDeps.length > 0) {
      lines.push("## Component Dependencies");
      lines.push("");
      lines.push("Key imports for each component:");
      lines.push("");

      for (const dep of interestingDeps) {
        const parts: string[] = [];
        if (dep.imports.utilities.length > 0) {
          parts.push(dep.imports.utilities.join(", "));
        }
        if (dep.imports.designSystem.length > 0) {
          parts.push(dep.imports.designSystem.join(", "));
        }
        if (dep.imports.radix.length > 0) {
          parts.push(`@radix-ui/${dep.imports.radix.join(", @radix-ui/")}`);
        }

        if (parts.length > 0) {
          lines.push(`- **${dep.component}** → ${parts.join(", ")}`);
        }
      }
      lines.push("");
    }
  }

  // Import Graph Section (hub files, circular deps, external deps)
  if (importGraph) {
    lines.push(formatImportGraph(importGraph));
  }

  // Component Variants Section
  if (variants.length > 0) {
    lines.push("## Component Variants");
    lines.push("");
    lines.push("Components with CVA variants (use these instead of custom styling):");
    lines.push("");

    for (const v of variants) {
      const variantTypes = Object.entries(v.variants)
        .map(([type, options]) => `${type}: ${options.join(", ")}`)
        .join(" | ");

      lines.push(`- **${v.component}** — ${variantTypes}`);
      if (v.defaultVariants) {
        const defaults = Object.entries(v.defaultVariants)
          .map(([k, val]) => `${k}="${val}"`)
          .join(", ");
        lines.push(`  - Defaults: ${defaults}`);
      }
    }
    lines.push("");
  }

  // API Routes Section (grouped by base path)
  if (apiRoutes.length > 0) {
    lines.push("## API Routes");
    lines.push("");

    // Count routes with schemas
    const routesWithSchemas = apiRoutes.filter(r =>
      r.requestSchema || r.responseSchema || r.querySchema
    ).length;

    if (routesWithSchemas > 0) {
      lines.push(`${apiRoutes.length} API endpoints (${routesWithSchemas} with schemas):`);
    } else {
      lines.push(`${apiRoutes.length} API endpoints:`);
    }
    lines.push("");

    // Group routes by base path
    const groupedRoutes = groupRoutesByBasePath(apiRoutes);
    const sortedGroups = Object.entries(groupedRoutes).sort((a, b) => a[0].localeCompare(b[0]));

    for (const [group, routes] of sortedGroups) {
      lines.push(`### ${group}`);
      lines.push("");
      for (const route of routes) {
        const methods = route.methods.join(", ");
        const auth = route.isProtected ? " 🔒" : "";
        lines.push(`- \`${methods}\` \`${route.path}\`${auth}`);

        // Add schema information (skip in compress/minimal modes)
        if (!compress && !minimal) {
          if (route.requestSchema && route.requestSchema.fields.length > 0) {
            lines.push(`  - **Request**: ${formatSchema(route.requestSchema, compact)}`);
          }
          if (route.querySchema && route.querySchema.fields.length > 0) {
            lines.push(`  - **Query**: ${formatSchema(route.querySchema, compact)}`);
          }
          if (route.responseSchema && route.responseSchema.fields.length > 0) {
            lines.push(`  - **Response**: ${formatSchema(route.responseSchema, compact)}`);
          }
        }
      }
      lines.push("");
    }
  }

  // GraphQL Schemas Section
  if (graphqlSchemas && graphqlSchemas.size > 0) {
    lines.push("## GraphQL Schemas");
    lines.push("");
    lines.push(`${graphqlSchemas.size} GraphQL type${graphqlSchemas.size === 1 ? "" : "s"} defined:`);
    lines.push("");

    // Group schemas by category
    const types: ApiSchema[] = [];
    const inputs: ApiSchema[] = [];
    const enums: ApiSchema[] = [];

    for (const schema of graphqlSchemas.values()) {
      if (schema.name?.endsWith("Input")) {
        inputs.push(schema);
      } else if (schema.fields.every(f => f.type === "enum")) {
        enums.push(schema);
      } else {
        types.push(schema);
      }
    }

    // Display Types
    if (types.length > 0 && !minimal) {
      lines.push(`### Types (${types.length})`);
      lines.push("");
      for (const schema of types.slice(0, compact ? 10 : 20)) {
        lines.push(`**${schema.name}**`);
        if (!compress) {
          lines.push("```graphql");
          lines.push(`type ${schema.name} {`);
          for (const field of schema.fields.slice(0, compact ? 5 : 10)) {
            const optional = field.isOptional ? "" : "!";
            lines.push(`  ${field.name}: ${field.type}${optional}`);
          }
          if (schema.fields.length > (compact ? 5 : 10)) {
            lines.push(`  # ... and ${schema.fields.length - (compact ? 5 : 10)} more fields`);
          }
          lines.push("}");
          lines.push("```");
        } else {
          // Compress mode - just show field names
          const fieldList = schema.fields.slice(0, 5).map(f => f.name).join(", ");
          const more = schema.fields.length > 5 ? `, +${schema.fields.length - 5} more` : "";
          lines.push(`  - ${fieldList}${more}`);
        }
        lines.push("");
      }
      if (types.length > (compact ? 10 : 20)) {
        lines.push(`... and ${types.length - (compact ? 10 : 20)} more types`);
        lines.push("");
      }
    }

    // Display Inputs
    if (inputs.length > 0 && !minimal) {
      lines.push(`### Inputs (${inputs.length})`);
      lines.push("");
      for (const schema of inputs.slice(0, compact ? 8 : 15)) {
        lines.push(`**${schema.name}**`);
        if (!compress) {
          lines.push("```graphql");
          lines.push(`input ${schema.name} {`);
          for (const field of schema.fields.slice(0, compact ? 5 : 10)) {
            const optional = field.isOptional ? "" : "!";
            lines.push(`  ${field.name}: ${field.type}${optional}`);
          }
          if (schema.fields.length > (compact ? 5 : 10)) {
            lines.push(`  # ... and ${schema.fields.length - (compact ? 5 : 10)} more fields`);
          }
          lines.push("}");
          lines.push("```");
        } else {
          // Compress mode
          const fieldList = schema.fields.slice(0, 5).map(f => f.name).join(", ");
          const more = schema.fields.length > 5 ? `, +${schema.fields.length - 5} more` : "";
          lines.push(`  - ${fieldList}${more}`);
        }
        lines.push("");
      }
      if (inputs.length > (compact ? 8 : 15)) {
        lines.push(`... and ${inputs.length - (compact ? 8 : 15)} more inputs`);
        lines.push("");
      }
    }

    // Display Enums
    if (enums.length > 0) {
      lines.push(`### Enums (${enums.length})`);
      lines.push("");
      for (const schema of enums.slice(0, 20)) {
        const values = schema.fields.map(f => f.name).join(" | ");
        lines.push(`- **${schema.name}**: ${values}`);
      }
      if (enums.length > 20) {
        lines.push(`- ... and ${enums.length - 20} more`);
      }
      lines.push("");
    }
  }

  // Database Models Section
  if (database && database.models.length > 0) {
    lines.push("## Database Models");
    lines.push("");
    lines.push(`${database.models.length} ${database.provider} models:`);
    lines.push("");

    for (const model of database.models) {
      const fieldList = model.fields.join(", ");
      lines.push(`- **${model.name}** — ${fieldList}`);

      if (model.relations.length > 0) {
        lines.push(`  - Relations: ${model.relations.join(", ")}`);
      }
    }
    lines.push("");
  }

  // Environment Variables Section
  if (envVars.length > 0) {
    lines.push("## Environment Variables");
    lines.push("");

    // Group by category if available
    const required = envVars.filter(e => e.required);
    const optional = envVars.filter(e => !e.required);

    if (required.length > 0) {
      lines.push("### Required");
      lines.push("");
      lines.push("```bash");
      for (const env of required) {
        const desc = env.description ? `  # ${env.description}` : "";
        lines.push(`${env.name}${desc}`);
      }
      lines.push("```");
      lines.push("");
    }

    if (optional.length > 0) {
      lines.push("### Optional");
      lines.push("");
      lines.push("```bash");
      for (const env of optional) {
        const desc = env.description ? `  # ${env.description}` : "";
        lines.push(`${env.name}${desc}`);
      }
      lines.push("```");
      lines.push("");
    }
  }

  // Detected Patterns Section
  if (patterns.patterns.length > 0) {
    lines.push("## Code Patterns");
    lines.push("");
    lines.push("Detected patterns in this codebase:");
    lines.push("");

    for (const pattern of patterns.patterns) {
      lines.push(`- ${pattern}`);
    }
    lines.push("");

    // Form pattern guidance
    if (patterns.hasReactHookForm && patterns.hasZod) {
      lines.push("### Form Pattern");
      lines.push("");
      lines.push("```typescript");
      lines.push('import { useForm } from "react-hook-form";');
      lines.push('import { zodResolver } from "@hookform/resolvers/zod";');
      lines.push('import { z } from "zod";');
      lines.push("");
      lines.push("const schema = z.object({");
      lines.push('  name: z.string().min(1, "Required"),');
      lines.push('  email: z.string().email(),');
      lines.push("});");
      lines.push("");
      lines.push("const form = useForm({");
      lines.push("  resolver: zodResolver(schema),");
      lines.push("});");
      lines.push("```");
      lines.push("");
    }
  }

  // Design Tokens
  if (Object.keys(tokens.colors).length > 0) {
    lines.push("## Design Tokens");
    lines.push("");

    // Mode object documentation if present
    if (utilities.hasMode) {
      lines.push("### Using the `mode` Object");
      lines.push("");
      lines.push("```typescript");
      lines.push(`import { mode } from "${utilities.modePath}";`);
      lines.push(`import { cn } from "${utilities.cnPath || "@/lib/utils"}";`);
      lines.push("");
      lines.push("// Usage in components:");
      lines.push("className={cn(");
      lines.push('  "base-styles",');
      lines.push("  mode.radius,        // Dynamic border radius");
      lines.push("  mode.color.bg.surface,");
      lines.push("  mode.typography.body.m");
      lines.push(")}");
      lines.push("```");
      lines.push("");
    }

    lines.push("### Color Tokens");
    lines.push("");
    lines.push("**Use semantic classes, never hardcoded colors:**");
    lines.push("");
    lines.push("```");
    lines.push("// Backgrounds");
    lines.push("bg-background, bg-card, bg-muted, bg-primary, bg-secondary, bg-destructive, bg-accent");
    lines.push("");
    lines.push("// Text");
    lines.push("text-foreground, text-muted-foreground, text-primary-foreground, text-destructive");
    lines.push("");
    lines.push("// Borders");
    lines.push("border-border, border-primary, border-destructive");
    lines.push("");
    lines.push("// NEVER USE:");
    lines.push("// bg-surface, bg-on-surface, bg-secondary-container, text-muted-foreground, #ffffff, rgb(...)");
    lines.push("```");
    lines.push("");

    // Show actual token values (collapsed for reference)
    if (Object.keys(tokens.colors).length > 0) {
      lines.push("<details>");
      lines.push("<summary>Raw CSS Variables (click to expand)</summary>");
      lines.push("");
      lines.push("```css");
      for (const [name, value] of Object.entries(tokens.colors)) {
        lines.push(`--${name}: ${value};`);
      }
      lines.push("```");
      lines.push("");
      lines.push("</details>");
      lines.push("");
    }
  }

  // Anti-Patterns Section (additional patterns not covered in Critical Rules)
  // Only show in full mode, and only framework-specific patterns
  if (!compress && !compact && antiPatterns && antiPatterns.patterns.length > 0) {
    const additionalPatterns = antiPatterns.patterns.filter(p =>
      p.title.includes("Next.js") ||
      p.title.includes("TypeScript") ||
      p.title.includes("API") ||
      p.title.includes("'use client'")
    );
    if (additionalPatterns.length > 0) {
      lines.push("## Additional Guidelines");
      lines.push("");
      for (const pattern of additionalPatterns.slice(0, 5)) {
        lines.push(`**${pattern.title}**`);
        lines.push(`- Wrong: \`${pattern.wrong.split('\n')[0]}\``);
        lines.push(`- Right: \`${pattern.right.split('\n')[0]}\``);
        lines.push("");
      }
    }
  }

  // AI Configuration Section
  if (aiRecommendations && !minimal && !compress) {
    lines.push("## AI Assistant Configuration");
    lines.push("");
    lines.push("**Recommended Settings Based on Codebase Complexity:**");
    lines.push("");

    // Overall recommendations
    const simpleModelDesc = aiRecommendations.simpleModel === "minimal"
      ? "minimal effort (fast, low-cost models)"
      : "standard effort (balanced cost/capability)";
    const complexModelDesc = aiRecommendations.complexModel === "maximum"
      ? "maximum effort (most capable models, extended thinking)"
      : "standard effort (balanced cost/capability)";

    lines.push(`- **For simple tasks** (formatting, typing): ${simpleModelDesc}`);
    lines.push(`- **For complex tasks** (refactoring, architecture): ${complexModelDesc}`);
    lines.push("");

    // Area-specific recommendations
    if (aiRecommendations.areas.length > 0) {
      lines.push("**Complexity by Area:**");
      lines.push("");
      for (const area of aiRecommendations.areas.slice(0, 5)) {
        const icon = area.level === "high" ? "🔴" : area.level === "medium" ? "🟡" : "🟢";
        const effort = area.level === "high"
          ? "Maximum effort (most capable model)"
          : area.level === "medium"
          ? "Standard effort (balanced model)"
          : "Minimal effort (fast, low-cost model)";
        lines.push(`- ${icon} **${area.name}** (${area.fileCount} files, complexity: ${area.avgScore}/100)`);
        lines.push(`  - Recommended: ${effort}`);
        if (area.characteristics.length > 0) {
          lines.push(`  - Characteristics: ${area.characteristics.join(", ")}`);
        }
      }
      lines.push("");
    }

    // High complexity files warning
    if (aiRecommendations.complexFiles.length > 0 && !compact) {
      const topComplex = aiRecommendations.complexFiles.slice(0, 3);
      lines.push("**High Complexity Files** (use most capable model with extended thinking):");
      lines.push("");
      for (const file of topComplex) {
        const miTag = file.maintainabilityIndex != null
          ? `, MI: ${file.maintainabilityIndex}`
          : "";
        lines.push(`- \`${file.path}\` (${file.lines} lines, score: ${file.score}/100${miTag})`);
        if (file.reasons.length > 0) {
          lines.push(`  - ${file.reasons.join(", ")}`);
        }
      }
      lines.push("");
    }

    // Function hotspots table — top 10 functions by cognitive complexity
    const allFunctions = aiRecommendations.complexFiles
      .flatMap((f: FileComplexity) =>
        (f.functions ?? []).map((fn: FunctionComplexity) => ({ ...fn, file: f.path }))
      )
      .sort((a: any, b: any) => b.cognitive - a.cognitive)
      .slice(0, 10);

    if (allFunctions.length > 0 && !compact && !compress) {
      lines.push("**Function Hotspots** (highest cognitive complexity):");
      lines.push("");
      lines.push("| Function | File | Cyclomatic | Cognitive | MI |");
      lines.push("|---|---|---|---|---|");
      for (const fn of allFunctions) {
        lines.push(
          `| ${fn.name} | ${fn.file}:${fn.startLine} | ${fn.cyclomatic} | ${fn.cognitive} | ${fn.maintainabilityIndex} |`
        );
      }
      lines.push("");
    }
  }

  // Commands Section
  if (commands.dev || commands.build || Object.keys(commands.custom).length > 0) {
    lines.push("## Commands");
    lines.push("");
    lines.push("```bash");
    if (commands.dev) lines.push(`npm run dev          # ${commands.dev}`);
    if (commands.build) lines.push(`npm run build        # ${commands.build}`);
    if (commands.test) lines.push(`npm test             # ${commands.test}`);
    if (commands.lint) lines.push(`npm run lint         # ${commands.lint}`);
    if (commands.typecheck) lines.push(`npm run typecheck    # ${commands.typecheck}`);
    lines.push("```");
    lines.push("");

    // Database commands
    if (commands.db && Object.keys(commands.db).length > 0) {
      lines.push("### Database");
      lines.push("");
      lines.push("```bash");
      for (const [name, cmd] of Object.entries(commands.db)) {
        lines.push(`npm run ${name}`);
      }
      lines.push("```");
      lines.push("");
    }

    // Custom/AI commands
    if (Object.keys(commands.custom).length > 0) {
      lines.push("### Other Commands");
      lines.push("");
      lines.push("```bash");
      for (const [name] of Object.entries(commands.custom).slice(0, 10)) {
        lines.push(`npm run ${name}`);
      }
      lines.push("```");
      lines.push("");
    }
  }

  // AI Automation Hooks (inspired by Latent-K)
  if (latentHooks && latentHooks.length > 0 && !minimal) {
    lines.push("## AI Automation Hooks");
    lines.push("");
    lines.push("These hooks automate common development tasks during your session:");
    lines.push("");
    for (const hook of latentHooks) {
      const patternDesc = hook.pattern ? ` (for \`${hook.pattern}\`)` : "";
      lines.push(`- **${hook.event}**: \`${hook.command}\`${patternDesc}`);
      if (hook.description) {
        lines.push(`  - ${hook.description}`);
      }
    }
    lines.push("");
  }

  // Reference to existing docs
  const hasExistingDocs = existingContext.hasClaudeMd || existingContext.hasAiFolder ||
    existingContext.hasCursorRules || existingContext.hasWindsurfRules ||
    existingContext.hasClineRules || existingContext.hasGeminiMd ||
    existingContext.hasCopilotInstructions || existingContext.hasCursorMdc;

  if (hasExistingDocs) {
    lines.push("## Existing AI Context Files");
    lines.push("");
    if (existingContext.hasClaudeMd) {
      lines.push(`- **${existingContext.claudeMdPath}** — Claude Code instructions`);
    }
    if (existingContext.hasCursorRules) {
      lines.push("- **.cursorrules** — Cursor AI rules");
    }
    if (existingContext.hasCursorMdc) {
      for (const file of existingContext.cursorMdcFiles) {
        lines.push(`- **${file}** — Cursor MDC rules`);
      }
    }
    if (existingContext.hasWindsurfRules) {
      lines.push("- **.windsurfrules** — Windsurf rules");
    }
    if (existingContext.hasClineRules) {
      lines.push("- **.clinerules** — Cline/Roo Code rules");
    }
    if (existingContext.hasGeminiMd) {
      lines.push("- **GEMINI.md** — Google Gemini CLI instructions");
    }
    if (existingContext.hasCopilotInstructions) {
      lines.push("- **copilot-instructions.md** — GitHub Copilot instructions");
    }
    if (existingContext.hasAiFolder) {
      lines.push(`- **.ai/ folder** — AI-native context files:`);
      for (const file of existingContext.aiFiles) {
        lines.push(`  - \`${file}\``);
      }
    }
    lines.push("");
  }

  // User-editable section — preserve existing content or add default placeholder
  const existingUserSection = options.existingContent
    ? extractUserSection(options.existingContent)
    : null;

  if (existingUserSection) {
    lines.push(existingUserSection);
  } else {
    lines.push("<!-- user:start -->");
    lines.push("## Custom Notes");
    lines.push("");
    lines.push("<!-- Add your custom project notes here. This section is preserved across regenerations. -->");
    lines.push("");
    lines.push("<!-- user:end -->");
  }
  lines.push("");

  return lines.join("\n");
}

/**
 * Extracts the user-editable section from existing file content
 * Preserves content between <!-- user:start --> and <!-- user:end --> markers
 */
function extractUserSection(content: string): string | null {
  const startMarker = "<!-- user:start -->";
  const endMarker = "<!-- user:end -->";
  const startIdx = content.indexOf(startMarker);
  const endIdx = content.indexOf(endMarker);

  if (startIdx !== -1 && endIdx !== -1 && endIdx > startIdx) {
    return content.slice(startIdx, endIdx + endMarker.length);
  }

  return null;
}

function getFrameworkRules(framework: Framework, tokens: Tokens, utilities: Utilities): string[] {
  const rules: string[] = [];

  // Next.js rules
  if (framework.name === "Next.js") {
    if (framework.router === "App Router") {
      rules.push("Use `'use client'` directive only when component needs interactivity");
      rules.push("Prefer Server Components by default");
      rules.push("Use `next/image` for images, `next/link` for navigation");
    }
  }

  // Tailwind rules
  if (framework.styling === "Tailwind CSS") {
    rules.push("Never use arbitrary values (`w-[137px]`) — use scale values");
    if (Object.keys(tokens.radius).length > 0) {
      rules.push("Use design system radius tokens, not arbitrary rounded values");
    }
  }

  // shadcn/ui rules
  if (utilities.hasShadcn) {
    rules.push("Use `asChild` prop when wrapping components with custom elements");
    rules.push("Use CVA variants for consistent component styling");
  }

  // TypeScript rules
  if (framework.language === "TypeScript") {
    rules.push("Type all props and function parameters");
    rules.push("Avoid `any` — use proper types or `unknown`");
  }

  return rules;
}

function groupRoutesByBasePath(routes: ApiRoute[]): Record<string, ApiRoute[]> {
  const grouped: Record<string, ApiRoute[]> = {};

  for (const route of routes) {
    // Extract base path: /api/users/[id] -> Users
    const parts = route.path.split("/").filter(Boolean);
    // Skip "api" prefix if present
    const startIndex = parts[0] === "api" ? 1 : 0;
    const basePath = parts[startIndex] || "root";

    // Format group name: users -> Users, user-settings -> User Settings
    const groupName = basePath
      .replace(/\[.*?\]/g, "") // Remove dynamic segments
      .replace(/-/g, " ")
      .split(" ")
      .filter(Boolean)
      .map(word => word.charAt(0).toUpperCase() + word.slice(1))
      .join(" ") || "Other";

    if (!grouped[groupName]) {
      grouped[groupName] = [];
    }
    grouped[groupName].push(route);
  }

  return grouped;
}

/**
 * Formats an API schema for display
 * Compact mode shows fewer fields, normal shows up to 5
 */
function formatSchema(schema: ApiSchema, compact: boolean = false): string {
  const maxFields = compact ? 3 : 5;
  const typeName = schema.name ? `${schema.name} ` : '';

  const fields = schema.fields.slice(0, maxFields).map(f => {
    const optional = f.isOptional ? '?' : '';
    const validations = f.validations && f.validations.length > 0
      ? ` (${f.validations.join(', ')})`
      : '';

    // Show nested indicator
    const nested = f.nested && f.nested.length > 0 ? ' {...}' : '';

    return `${f.name}${optional}: ${f.type}${validations}${nested}`;
  });

  const remaining = schema.fields.length - maxFields;
  const more = remaining > 0 ? `, +${remaining} more` : '';

  return `${typeName}{ ${fields.join(', ')}${more} }`;
}

/**
 * Generate minimal output (~3K tokens)
 * TL;DR + Rules with inline examples + Component names only
 */
function generateMinimalOutput(result: ScanResult, options: GeneratorOptions): string {
  const { components, framework, utilities, hooks, apiRoutes, database, importGraph, graphqlSchemas, latentHooks } = result;
  const lines: string[] = [];

  // Header
  lines.push("# AGENTS.md");
  lines.push("");
  lines.push("> Minimal output • [hashmark](https://hashmark.md)");
  lines.push("");

  // Quick Reference
  lines.push("## Quick Reference");
  lines.push("");
  const stackParts: string[] = [framework.name];
  if (framework.language === "TypeScript") stackParts.push("TypeScript");
  if (framework.styling) stackParts.push(framework.styling);
  lines.push(`**Stack**: ${stackParts.join(" + ")}`);
  lines.push(`**Components**: ${components.length} — USE EXISTING`);
  if (utilities.hasCn) lines.push(`**Utility**: \`cn()\` from \`${utilities.cnPath}\``);
  if (utilities.hasMode) lines.push(`**Design**: \`mode\` from \`${utilities.modePath}\``);
  if (database) lines.push(`**Database**: ${database.provider} (${database.models.length} models)`);
  if (graphqlSchemas && graphqlSchemas.size > 0) lines.push(`**GraphQL**: ${graphqlSchemas.size} schemas`);
  lines.push("");

  // Rules (compact with inline examples)
  lines.push("## Rules");
  lines.push("");
  lines.push("1. **USE EXISTING COMPONENTS** — Don't create new ones");
  lines.push("   - WRONG: `<div className=\"rounded border\">` → RIGHT: `<Card>`");
  lines.push("");
  lines.push("2. **USE DESIGN TOKENS** — No hardcoded colors");
  lines.push("   - WRONG: `bg-blue-500` → RIGHT: `bg-primary`");
  lines.push("");
  if (utilities.hasCn) {
    lines.push("3. **USE `cn()`** — For conditional classes");
    lines.push("   - WRONG: `\"btn \" + (x ? \"active\" : \"\")` → RIGHT: `cn(\"btn\", x && \"active\")`");
    lines.push("");
  }
  if (framework.name === "Next.js") {
    lines.push(`${utilities.hasCn ? "4" : "3"}. **NEXT.JS** — Use Link/Image, prefer Server Components`);
    lines.push("");
  }

  // Components (names only, grouped)
  lines.push("## Components");
  lines.push("");
  const grouped = groupComponentsByDirectory(components);
  for (const [dir, comps] of Object.entries(grouped)) {
    const groupName = formatDirectoryName(dir);
    const names = comps.map(c => c.name).join(", ");
    lines.push(`**${groupName}**: ${names}`);
  }
  lines.push("");

  // Hooks (if any)
  if (hooks.length > 0) {
    lines.push("## Hooks");
    lines.push("");
    lines.push(hooks.map(h => `\`${h.name}\``).join(", "));
    lines.push("");
  }

  // Hub files (most impactful)
  if (importGraph && importGraph.hubFiles.length > 0) {
    lines.push("## High-Impact Files");
    lines.push("");
    for (const hub of importGraph.hubFiles.slice(0, 5)) {
      lines.push(`- \`${hub.file}\` (${hub.importedByCount} dependents)`);
    }
    lines.push("");
  }

  // AI Automation Hooks
  if (latentHooks && latentHooks.length > 0) {
    lines.push("## AI Automation Hooks");
    lines.push("");
    const hooksList = latentHooks.map(h => `**${h.event}**: \`${h.command}\``).join(", ");
    lines.push(hooksList);
    lines.push("");
  }

  return lines.join("\n");
}

/**
 * Generate XML-structured output (industry standard, matches Repomix)
 */
function generateXmlOutput(result: ScanResult): string {
  const { components, tokens, framework, utilities, hooks, apiRoutes, database, importGraph, graphqlSchemas, latentHooks } = result;
  const lines: string[] = [];

  lines.push('<?xml version="1.0" encoding="UTF-8"?>');
  lines.push('<agents-context version="1.0">');
  lines.push('');

  // Summary
  lines.push('  <summary>');
  const stackParts: string[] = [framework.name];
  if (framework.language === "TypeScript") stackParts.push("TypeScript");
  if (framework.styling) stackParts.push(framework.styling);
  lines.push(`    <stack>${stackParts.join(" + ")}</stack>`);
  lines.push(`    <components count="${components.length}">USE EXISTING - don't create new</components>`);
  if (utilities.hasCn) lines.push(`    <utility name="cn" path="${escapeXml(utilities.cnPath || '')}" />`);
  if (utilities.hasMode) lines.push(`    <utility name="mode" path="${escapeXml(utilities.modePath || '')}" />`);
  if (database) lines.push(`    <database provider="${database.provider}" models="${database.models.length}" />`);
  if (graphqlSchemas && graphqlSchemas.size > 0) lines.push(`    <graphql schemas="${graphqlSchemas.size}" />`);
  lines.push('  </summary>');
  lines.push('');

  // Rules with examples
  lines.push('  <rules priority="critical">');
  lines.push('    <rule name="use-existing-components">');
  lines.push(`      <description>This project has ${components.length} components. Check before creating new.</description>`);
  lines.push('      <example type="wrong"><![CDATA[<div className="rounded border p-4">...</div>]]></example>');
  lines.push('      <example type="right"><![CDATA[<Card><CardContent>...</CardContent></Card>]]></example>');
  lines.push('    </rule>');
  lines.push('    <rule name="use-design-tokens">');
  lines.push('      <description>Never hardcode colors. Use semantic tokens.</description>');
  lines.push('      <example type="wrong"><![CDATA[className="bg-blue-500 text-on-surface"]]></example>');
  lines.push('      <example type="right"><![CDATA[className="bg-primary text-primary-foreground"]]></example>');
  lines.push('    </rule>');
  if (utilities.hasCn) {
    lines.push('    <rule name="use-cn-utility">');
    lines.push(`      <description>Import from ${escapeXml(utilities.cnPath || '')}. Use for conditional classes.</description>`);
    lines.push('      <example type="wrong"><![CDATA[className={"btn " + (active ? "active" : "")}]]></example>');
    lines.push('      <example type="right"><![CDATA[className={cn("btn", active && "active")}]]></example>');
    lines.push('    </rule>');
  }
  if (utilities.hasMode) {
    lines.push('    <rule name="use-mode-design-system">');
    lines.push(`      <description>Import from ${escapeXml(utilities.modePath || '')}. Theme-aware styling.</description>`);
    lines.push('      <example type="wrong"><![CDATA[className="rounded-lg"]]></example>');
    lines.push('      <example type="right"><![CDATA[className={cn("...", mode.radius)}]]></example>');
    lines.push('    </rule>');
  }
  lines.push('  </rules>');
  lines.push('');

  // Components
  lines.push(`  <components count="${components.length}">`);
  const grouped = groupComponentsByDirectory(components);
  for (const [dir, comps] of Object.entries(grouped)) {
    const groupName = formatDirectoryName(dir);
    lines.push(`    <group name="${escapeXml(groupName)}" count="${comps.length}">`);
    for (const comp of comps) {
      const propsAttr = comp.props && comp.props.length > 0 ? ` props="${escapeXml(comp.props.slice(0, 5).join(", "))}"` : '';
      lines.push(`      <component name="${escapeXml(comp.name)}" path="${escapeXml(comp.importPath)}"${propsAttr} />`);
    }
    lines.push('    </group>');
  }
  lines.push('  </components>');
  lines.push('');

  // Hooks
  if (hooks.length > 0) {
    lines.push(`  <hooks count="${hooks.length}">`);
    for (const hook of hooks) {
      lines.push(`    <hook name="${escapeXml(hook.name)}" path="${escapeXml(hook.importPath)}"${hook.isClientOnly ? ' client-only="true"' : ''} />`);
    }
    lines.push('  </hooks>');
    lines.push('');
  }

  // Hub files
  if (importGraph && importGraph.hubFiles.length > 0) {
    lines.push('  <hub-files description="Changes to these affect many files">');
    for (const hub of importGraph.hubFiles.slice(0, 8)) {
      lines.push(`    <file path="${escapeXml(hub.file)}" dependents="${hub.importedByCount}" />`);
    }
    lines.push('  </hub-files>');
    lines.push('');
  }

  // API routes
  if (apiRoutes.length > 0) {
    lines.push(`  <api-routes count="${apiRoutes.length}">`);
    for (const route of apiRoutes.slice(0, 20)) {
      const methods = route.methods.join(",");
      lines.push(`    <route path="${escapeXml(route.path)}" methods="${methods}"${route.isProtected ? ' protected="true"' : ''} />`);
    }
    lines.push('  </api-routes>');
    lines.push('');
  }

  // GraphQL schemas
  if (graphqlSchemas && graphqlSchemas.size > 0) {
    lines.push(`  <graphql-schemas count="${graphqlSchemas.size}">`);
    for (const schema of Array.from(graphqlSchemas.values()).slice(0, 15)) {
      const fields = schema.fields.slice(0, 6).map(f => f.name).join(", ");
      lines.push(`    <schema name="${escapeXml(schema.name || 'unknown')}" fields="${escapeXml(fields)}" />`);
    }
    lines.push('  </graphql-schemas>');
    lines.push('');
  }

  // Database
  if (database && database.models.length > 0) {
    lines.push(`  <database provider="${database.provider}" models="${database.models.length}">`);
    for (const model of database.models.slice(0, 15)) {
      const fields = model.fields.slice(0, 6).join(", ");
      lines.push(`    <model name="${escapeXml(model.name)}" fields="${escapeXml(fields)}" />`);
    }
    lines.push('  </database>');
    lines.push('');
  }

  // Design tokens
  if (Object.keys(tokens.colors).length > 0) {
    lines.push('  <design-tokens>');
    lines.push('    <colors>bg-background, bg-card, bg-muted, bg-primary, bg-secondary, bg-destructive</colors>');
    lines.push('    <text>text-foreground, text-muted-foreground, text-primary-foreground</text>');
    lines.push('    <borders>border-border, border-primary</borders>');
    lines.push('    <forbidden>bg-surface, bg-on-surface, bg-gray-*, #hexvalues</forbidden>');
    lines.push('  </design-tokens>');
    lines.push('');
  }

  // AI Automation Hooks
  if (latentHooks && latentHooks.length > 0) {
    lines.push('  <automation-hooks>');
    for (const hook of latentHooks) {
      const descAttr = hook.description ? ` description="${escapeXml(hook.description)}"` : '';
      const patternAttr = hook.pattern ? ` pattern="${escapeXml(hook.pattern)}"` : '';
      lines.push(`    <hook event="${escapeXml(hook.event)}" command="${escapeXml(hook.command)}"${descAttr}${patternAttr} />`);
    }
    lines.push('  </automation-hooks>');
    lines.push('');
  }

  lines.push('</agents-context>');
  return lines.join("\n");
}

function escapeXml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

/**
 * Generate Getting Started section based on detected patterns
 */
function generateGettingStarted(result: ScanResult): string | null {
  const { commands, database, envVars, framework } = result;
  const steps: string[] = [];

  // 1. Install dependencies
  steps.push("npm install");

  // 2. Environment setup (if env vars detected)
  if (envVars.length > 0) {
    steps.push("");
    steps.push("# Set up environment");
    steps.push("cp .env.example .env.local");
    steps.push("# Edit .env.local with your values");
  }

  // 3. Database setup (if database detected)
  if (database) {
    steps.push("");
    steps.push("# Database setup");
    if (database.provider === "prisma") {
      if (commands.db?.["db:push"]) {
        steps.push("npm run db:push");
      } else if (commands.db?.push) {
        steps.push("npm run db:push");
      } else {
        steps.push("npx prisma db push");
      }
      if (commands.db?.seed || commands.db?.["db:seed"]) {
        steps.push("npm run db:seed    # Optional: seed test data");
      }
    } else if (database.provider === "drizzle") {
      if (commands.db?.push) {
        steps.push("npm run db:push");
      } else {
        steps.push("npx drizzle-kit push");
      }
    }
  }

  // 4. Dev server
  steps.push("");
  steps.push("# Start development");
  if (commands.dev) {
    steps.push("npm run dev");
  } else {
    steps.push("npm run dev");
  }

  // Only generate if we have meaningful content
  if (steps.length <= 3) {
    return null;
  }

  const lines: string[] = [];
  lines.push("## Getting Started");
  lines.push("");
  lines.push("```bash");
  lines.push(...steps);
  lines.push("```");
  lines.push("");

  return lines.join("\n");
}
