/**
 * Hook Installer
 *
 * Manages Claude Code hooks integration for runtime context injection.
 * - `hashmark hook install` — Creates PreToolUse hook that injects file
 *   relationships when Claude reads a file
 * - `hashmark hook install --pre-commit` — Also installs git pre-commit hook
 * - `hashmark hook uninstall` — Removes hashmark hooks
 *
 * @module hooks/install
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync, chmodSync, unlinkSync } from "fs";
import { join, resolve } from "path";
import pc from "picocolors";

interface InstallOptions {
  preCommit?: boolean;
}

/**
 * Installs Claude Code hooks for runtime context injection.
 *
 * 1. Generates `.hashmark/hooks/context-inject.mjs` — standalone hook script
 * 2. Merges PreToolUse hook config into `.claude/settings.json`
 * 3. Optionally installs pre-commit hook
 */
export async function installHooks(dir: string, options: InstallOptions = {}): Promise<void> {
  const absDir = resolve(dir);

  console.log(pc.cyan("\n  # hashmark hook install\n"));

  // 1. Generate the hook script
  generateHookScript(absDir);

  // 2. Update Claude Code settings
  updateClaudeSettings(absDir);

  // 3. Optionally install pre-commit hook
  if (options.preCommit) {
    installPreCommitHook(absDir);
  }

  console.log(pc.green("\n    ✓ Hooks installed successfully"));
  console.log(pc.dim("      Run 'hashmark sync' to build the relationship index\n"));
}

/**
 * Removes hashmark hooks from Claude Code settings and deletes hook files.
 */
export async function uninstallHooks(dir: string): Promise<void> {
  const absDir = resolve(dir);

  console.log(pc.cyan("\n  # hashmark hook uninstall\n"));

  // Remove hook script
  const hookScript = join(absDir, ".hashmark", "hooks", "context-inject.mjs");
  if (existsSync(hookScript)) {
    unlinkSync(hookScript);
    console.log(pc.dim("    Removed .hashmark/hooks/context-inject.mjs"));
  }

  // Remove from Claude Code settings
  const settingsPath = join(absDir, ".claude", "settings.json");
  if (existsSync(settingsPath)) {
    try {
      const settings = JSON.parse(readFileSync(settingsPath, "utf-8"));
      if (settings.hooks?.PreToolUse) {
        settings.hooks.PreToolUse = settings.hooks.PreToolUse.filter(
          (matcher: HookMatcher) => !isHashmarkHook(matcher)
        );
        if (settings.hooks.PreToolUse.length === 0) {
          delete settings.hooks.PreToolUse;
        }
        if (Object.keys(settings.hooks).length === 0) {
          delete settings.hooks;
        }
        writeFileSync(settingsPath, JSON.stringify(settings, null, 2) + "\n", "utf-8");
        console.log(pc.dim("    Removed hashmark hook from .claude/settings.json"));
      }
    } catch {
      // Settings file corrupt — nothing to clean
    }
  }

  // Remove pre-commit hook content
  removePreCommitHook(absDir);

  console.log(pc.green("\n    ✓ Hooks uninstalled\n"));
}

// --- Internal helpers ---

interface HookEntry {
  type: string;
  command: string;
  timeout?: number;
}

interface HookMatcher {
  matcher?: string;
  hooks: HookEntry[];
}

interface ClaudeSettings {
  hooks?: {
    PreToolUse?: HookMatcher[];
    [key: string]: unknown;
  };
  [key: string]: unknown;
}

/** Check if a hook matcher belongs to hashmark */
function isHashmarkHook(matcher: HookMatcher): boolean {
  return matcher.hooks?.some(h => h.command?.includes(".hashmark/hooks/")) ?? false;
}

/**
 * Generates the standalone context-inject.mjs hook script.
 * This script is self-contained — no imports from hashmark internals.
 */
function generateHookScript(dir: string): void {
  const hooksDir = join(dir, ".hashmark", "hooks");
  if (!existsSync(hooksDir)) {
    mkdirSync(hooksDir, { recursive: true });
  }

  const script = `#!/usr/bin/env node
/**
 * hashmark context-inject hook
 *
 * Claude Code PreToolUse hook — injects rich file relationship context
 * (export signatures + usage mapping) when the Read tool is used.
 *
 * Generated by: hashmark hook install
 * Regenerate with: hashmark hook install
 */

import { readFileSync } from "fs";
import { dirname, join, resolve, relative } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

let input = "";
process.stdin.setEncoding("utf-8");
process.stdin.on("data", (chunk) => { input += chunk; });
process.stdin.on("end", () => {
  try {
    const event = JSON.parse(input);
    if (event.tool_name !== "Read") process.exit(0);

    const filePath = event.tool_input?.file_path;
    if (!filePath) process.exit(0);

    const indexPath = join(__dirname, "..", "index.json");
    let index;
    try {
      index = JSON.parse(readFileSync(indexPath, "utf-8"));
    } catch {
      process.exit(0);
    }

    const projectRoot = index.projectRoot || resolve(__dirname, "../..");
    const relPath = relative(projectRoot, resolve(filePath)).replace(/\\\\/g, "/");

    const info = index.files[relPath] || index.files[relPath.replace(/\\\\/g, "/")];
    if (!info) process.exit(0);

    formatAndOutput(relPath, info);
  } catch {
    process.exit(0);
  }
});

function formatAndOutput(path, info) {
  const lines = ["[hashmark context] " + path];

  // Exports with signatures — most useful for understanding what a file provides
  if (info.exports && info.exports.length > 0) {
    lines.push("");
    lines.push("Exports:");
    for (const exp of info.exports.slice(0, 12)) {
      if (typeof exp === "string") {
        lines.push("  " + exp);
      } else if (exp.signature) {
        lines.push("  " + exp.name + exp.signature);
      } else {
        lines.push("  " + exp.name + " (" + (exp.kind || "export") + ")");
      }
    }
    if (info.exports.length > 12) {
      lines.push("  ..." + (info.exports.length - 12) + " more");
    }
  }

  // Dependencies — what this file imports (compact, basename only to save tokens)
  if (info.imports && info.imports.length > 0) {
    lines.push("");
    const shown = info.imports.slice(0, 8).map(p => p.split("/").pop().replace(/\\..*$/, ""));
    const suffix = info.imports.length > 8 ? " (+" + (info.imports.length - 8) + " more)" : "";
    lines.push("Depends on: " + shown.join(", ") + suffix);
  }

  // Who uses this file and WHICH exports they pull — this is the key insight
  if (info.importUsage && Object.keys(info.importUsage).length > 0) {
    lines.push("");
    const total = info.importedBy ? info.importedBy.length : Object.keys(info.importUsage).length;
    lines.push("Used by " + total + " file(s):");
    const entries = Object.entries(info.importUsage).slice(0, 10);
    for (const [importer, symbols] of entries) {
      // Show last 2 path segments so "api/repos/route" is distinct from "api/scan/route"
      const parts = importer.replace(/\\..*$/, "").split("/");
      const importerName = parts.slice(-2).join("/");
      lines.push("  " + importerName + " → " + symbols.join(", "));
    }
    if (total > 10) lines.push("  ...+" + (total - 10) + " more");
  } else if (info.importedBy && info.importedBy.length > 0) {
    lines.push("");
    const shown = info.importedBy.slice(0, 6).map(p => {
      const parts = p.replace(/\\..*$/, "").split("/");
      return parts.slice(-2).join("/");
    });
    const suffix = info.importedBy.length > 6 ? " (+" + (info.importedBy.length - 6) + " more)" : "";
    lines.push("Used by: " + shown.join(", ") + suffix);
  }

  // Only inject if we have something useful beyond the header
  if (lines.length <= 1) process.exit(0);

  process.stdout.write(JSON.stringify({
    hookSpecificOutput: {
      hookEventName: "PreToolUse",
      additionalContext: lines.join("\\n"),
    },
  }));
  process.exit(0);
}
`;

  const scriptPath = join(hooksDir, "context-inject.mjs");
  writeFileSync(scriptPath, script, "utf-8");
  chmodSync(scriptPath, 0o755);
  console.log(pc.green("    ✓ Generated .hashmark/hooks/context-inject.mjs"));
}

/**
 * Merges hashmark PreToolUse hook into .claude/settings.json.
 * Preserves existing hooks and settings.
 */
function updateClaudeSettings(dir: string): void {
  const claudeDir = join(dir, ".claude");
  const settingsPath = join(claudeDir, "settings.json");

  // Load existing settings or create new
  let settings: ClaudeSettings = {};
  if (existsSync(settingsPath)) {
    try {
      settings = JSON.parse(readFileSync(settingsPath, "utf-8"));
    } catch {
      // Corrupt — start fresh
    }
  } else {
    if (!existsSync(claudeDir)) {
      mkdirSync(claudeDir, { recursive: true });
    }
  }

  // Ensure hooks structure
  if (!settings.hooks) {
    settings.hooks = {};
  }
  if (!settings.hooks.PreToolUse) {
    settings.hooks.PreToolUse = [];
  }

  // Remove existing hashmark hooks (to avoid duplicates on re-install)
  settings.hooks.PreToolUse = settings.hooks.PreToolUse.filter(
    (matcher: HookMatcher) => !isHashmarkHook(matcher)
  );

  // Add the hashmark hook
  settings.hooks.PreToolUse.push({
    matcher: "Read",
    hooks: [
      {
        type: "command",
        command: "node .hashmark/hooks/context-inject.mjs",
        timeout: 5,
      },
    ],
  });

  writeFileSync(settingsPath, JSON.stringify(settings, null, 2) + "\n", "utf-8");
  console.log(pc.green("    ✓ Updated .claude/settings.json"));
}

/**
 * Installs a pre-commit hook that runs hashmark sync + hashmark.
 * Detects husky, falls back to raw git hooks.
 */
function installPreCommitHook(dir: string): void {
  const hashmarkBlock = `
# --- hashmark pre-commit ---
npx hashmark sync
npx hashmark --force
git add AGENTS.md .hashmark/index.json 2>/dev/null || true
# --- end hashmark ---
`;

  // Check for husky
  const huskyDir = join(dir, ".husky");
  if (existsSync(huskyDir)) {
    const preCommitPath = join(huskyDir, "pre-commit");
    let existing = "";
    if (existsSync(preCommitPath)) {
      existing = readFileSync(preCommitPath, "utf-8");
      // Remove old hashmark block if present
      existing = existing.replace(/\n# --- hashmark pre-commit ---[\s\S]*?# --- end hashmark ---\n?/g, "");
    } else {
      existing = "#!/bin/sh\n";
    }
    writeFileSync(preCommitPath, existing.trimEnd() + "\n" + hashmarkBlock, "utf-8");
    chmodSync(preCommitPath, 0o755);
    console.log(pc.green("    ✓ Updated .husky/pre-commit"));
    return;
  }

  // Fall back to raw git hook
  const gitHooksDir = join(dir, ".git", "hooks");
  if (existsSync(join(dir, ".git"))) {
    if (!existsSync(gitHooksDir)) {
      mkdirSync(gitHooksDir, { recursive: true });
    }
    const preCommitPath = join(gitHooksDir, "pre-commit");
    let existing = "";
    if (existsSync(preCommitPath)) {
      existing = readFileSync(preCommitPath, "utf-8");
      existing = existing.replace(/\n# --- hashmark pre-commit ---[\s\S]*?# --- end hashmark ---\n?/g, "");
    } else {
      existing = "#!/bin/sh\n";
    }
    writeFileSync(preCommitPath, existing.trimEnd() + "\n" + hashmarkBlock, "utf-8");
    chmodSync(preCommitPath, 0o755);
    console.log(pc.green("    ✓ Updated .git/hooks/pre-commit"));
    return;
  }

  console.log(pc.yellow("    ! No .husky/ or .git/ found — skipping pre-commit hook"));
}

/** Removes hashmark block from pre-commit hooks */
function removePreCommitHook(dir: string): void {
  const paths = [
    join(dir, ".husky", "pre-commit"),
    join(dir, ".git", "hooks", "pre-commit"),
  ];

  for (const hookPath of paths) {
    if (existsSync(hookPath)) {
      let content = readFileSync(hookPath, "utf-8");
      const cleaned = content.replace(/\n# --- hashmark pre-commit ---[\s\S]*?# --- end hashmark ---\n?/g, "");
      if (cleaned !== content) {
        writeFileSync(hookPath, cleaned, "utf-8");
        console.log(pc.dim(`    Removed hashmark block from ${hookPath.replace(dir + "/", "")}`));
      }
    }
  }
}
