/**
 * CLAUDE.md Generator
 *
 * Generates project instructions for Claude Code.
 * Claude Code reads CLAUDE.md from the project root for context.
 *
 * Focus areas:
 * - Commands (build, test, lint, dev)
 * - Critical rules (ALWAYS/NEVER directives)
 * - Architecture overview
 * - Key patterns and file structure
 *
 * @module formats/claude-md
 */

import type { ScanResult } from "../types.js";

export function generateClaudeMd(scan: ScanResult, customRules: string[] = []): string {
  const { components, framework, hooks, utilities, commands, apiRoutes, envVars, patterns, database, stats, existingContext, barrels, importGraph, variants, latentHooks } = scan;
  const lines: string[] = [];

  lines.push("# CLAUDE.md");
  lines.push("");
  lines.push(`> Auto-generated by [hashmark](https://hashmark.md) — Project instructions for Claude Code`);
  lines.push("");

  // Project Overview
  lines.push("## Project Overview");
  lines.push("");
  const stackParts: string[] = [];
  if (framework.name !== "Unknown") {
    stackParts.push(framework.version ? `${framework.name} ${framework.version}` : framework.name);
  }
  if (framework.router) stackParts.push(framework.router);
  if (framework.language === "TypeScript") {
    stackParts.push(framework.versions?.typescript ? `TypeScript ${framework.versions.typescript}` : "TypeScript");
  }
  if (framework.styling) stackParts.push(framework.styling);
  if (utilities.hasShadcn) stackParts.push("shadcn/ui");
  if (database) stackParts.push(`${database.provider} (${database.models.length} models)`);

  lines.push(`**Stack**: ${stackParts.join(" • ")}`);
  if (stats) {
    lines.push(`**Codebase**: ${stats.totalFiles} files, ${stats.totalLines.toLocaleString()} lines, ${components.length} components`);
  }
  lines.push("");

  // Commands — Claude Code's most important section
  lines.push("## Commands");
  lines.push("");
  lines.push("```bash");
  if (commands.dev) lines.push(`# Development`);
  if (commands.dev) lines.push(`npm run dev`);
  if (commands.build) lines.push(`npm run build`);
  if (commands.test) lines.push(`npm test`);
  if (commands.lint) lines.push(`npm run lint`);
  if (commands.typecheck) lines.push(`npm run typecheck`);

  if (commands.db && Object.keys(commands.db).length > 0) {
    lines.push("");
    lines.push("# Database");
    for (const [name] of Object.entries(commands.db)) {
      lines.push(`npm run ${name}`);
    }
  }

  if (Object.keys(commands.custom).length > 0) {
    lines.push("");
    lines.push("# Other");
    for (const [name] of Object.entries(commands.custom).slice(0, 8)) {
      lines.push(`npm run ${name}`);
    }
  }
  lines.push("```");
  lines.push("");

  // Critical Rules — Claude Code responds well to direct, imperative rules
  lines.push("## Critical Rules");
  lines.push("");

  // Component reuse
  if (components.length > 0) {
    lines.push(`- **ALWAYS** check existing ${components.length} components before creating new ones`);
  }

  // Design tokens
  if (Object.keys(scan.tokens.colors).length > 0) {
    lines.push("- **NEVER** hardcode colors — use semantic tokens: `bg-primary`, `text-foreground`, `border-border`");
  }

  // Utilities
  if (utilities.hasCn) {
    lines.push(`- **ALWAYS** use \`cn()\` from \`${utilities.cnPath}\` for conditional classes`);
  }
  if (utilities.hasMode) {
    lines.push(`- **ALWAYS** use \`mode\` from \`${utilities.modePath}\` for theme-aware styling`);
  }

  // Framework-specific
  if (framework.name === "Next.js" && framework.router === "App Router") {
    lines.push("- **Prefer** Server Components by default — only add `'use client'` when needed");
    lines.push("- **ALWAYS** use `next/image` for images and `next/link` for navigation");
  }
  if (framework.language === "TypeScript") {
    lines.push("- **NEVER** use `any` — use proper types or `unknown`");
  }
  if (framework.styling === "Tailwind CSS") {
    lines.push("- **NEVER** use arbitrary values (`w-[137px]`) — use Tailwind scale values");
  }
  if (utilities.hasShadcn) {
    lines.push("- **ALWAYS** use CVA variants for component styling");
  }

  // Custom rules
  for (const rule of customRules) {
    lines.push(`- ${rule}`);
  }

  // Rules extracted from existing CLAUDE.md
  if (existingContext.hasClaudeMd && existingContext.claudeMdContent) {
    const existingLines = existingContext.claudeMdContent.split("\n");
    for (const line of existingLines) {
      if ((line.includes("NEVER") || line.includes("ALWAYS") || line.includes("MUST")) && line.trim().length > 20) {
        const cleanLine = line.replace(/^[\s\-\*\d\.]+/, "").trim();
        if (!lines.some(l => l.includes(cleanLine))) {
          lines.push(`- ${cleanLine}`);
        }
      }
    }
  }
  lines.push("");

  // Architecture — Key file locations
  lines.push("## Architecture");
  lines.push("");

  // Key imports
  if (utilities.hasCn || utilities.hasMode || barrels.length > 0) {
    lines.push("### Key Imports");
    lines.push("");
    lines.push("```typescript");
    if (utilities.hasCn) lines.push(`import { cn } from "${utilities.cnPath}";`);
    if (utilities.hasMode) lines.push(`import { mode } from "${utilities.modePath}";`);
    for (const barrel of barrels.slice(0, 3)) {
      const exports = barrel.exports.filter(e => !e.startsWith("*")).slice(0, 3).join(", ");
      if (exports) lines.push(`import { ${exports} } from "${barrel.importPath}";`);
    }
    lines.push("```");
    lines.push("");
  }

  // High-impact files
  if (importGraph && importGraph.hubFiles.length > 0) {
    lines.push("### High-Impact Files");
    lines.push("");
    lines.push("Changes to these files affect many dependents — edit carefully:");
    lines.push("");
    for (const hub of importGraph.hubFiles.slice(0, 6)) {
      lines.push(`- \`${hub.file}\` (${hub.importedByCount} dependents)`);
    }
    lines.push("");
  }

  // Components list (compact)
  if (components.length > 0) {
    lines.push("### Components");
    lines.push("");
    lines.push(`${components.length} components available. Check before creating new ones:`);
    lines.push("");

    const grouped: Record<string, string[]> = {};
    for (const comp of components) {
      const parts = comp.path.split("/");
      parts.pop();
      const dir = parts.pop() || "root";
      if (!grouped[dir]) grouped[dir] = [];
      grouped[dir].push(comp.name);
    }

    for (const [dir, names] of Object.entries(grouped)) {
      lines.push(`- **${dir}**: ${names.join(", ")}`);
    }
    lines.push("");
  }

  // Hooks
  if (hooks.length > 0) {
    lines.push("### Custom Hooks");
    lines.push("");
    for (const hook of hooks) {
      const clientNote = hook.isClientOnly ? " *(client only)*" : "";
      lines.push(`- \`${hook.name}\` from \`${hook.importPath}\`${clientNote}`);
    }
    lines.push("");
  }

  // API Routes
  if (apiRoutes.length > 0) {
    lines.push("### API Routes");
    lines.push("");
    for (const route of apiRoutes.slice(0, 20)) {
      const methods = route.methods.join(", ");
      const auth = route.isProtected ? " (auth)" : "";
      lines.push(`- \`${methods}\` \`${route.path}\`${auth}`);
    }
    lines.push("");
  }

  // Database Models
  if (database && database.models.length > 0) {
    lines.push("### Database Models");
    lines.push("");
    for (const model of database.models.slice(0, 15)) {
      const fields = model.fields.slice(0, 5).join(", ");
      const more = model.fields.length > 5 ? ` +${model.fields.length - 5}` : "";
      lines.push(`- **${model.name}**: ${fields}${more}`);
    }
    lines.push("");
  }

  // Environment Variables
  if (envVars.length > 0) {
    const required = envVars.filter(e => e.required);
    if (required.length > 0) {
      lines.push("### Required Environment Variables");
      lines.push("");
      lines.push("```bash");
      for (const env of required.slice(0, 15)) {
        lines.push(env.name);
      }
      lines.push("```");
      lines.push("");
    }
  }

  // Patterns
  if (patterns.patterns.length > 0) {
    lines.push("## Code Patterns");
    lines.push("");
    for (const pattern of patterns.patterns) {
      lines.push(`- ${pattern}`);
    }
    lines.push("");
  }

  // Design tokens (brief)
  if (Object.keys(scan.tokens.colors).length > 0) {
    lines.push("## Design Tokens");
    lines.push("");
    lines.push("Use semantic classes, never hardcoded colors:");
    lines.push("");
    lines.push("```");
    lines.push("bg-background, bg-card, bg-muted, bg-primary, bg-secondary, bg-destructive");
    lines.push("text-foreground, text-muted-foreground, text-primary-foreground");
    lines.push("border-border, border-primary");
    lines.push("```");
    lines.push("");
  }

  // AI Automation Hooks
  if (latentHooks && latentHooks.length > 0) {
    lines.push("## AI Automation Hooks");
    lines.push("");
    lines.push("Use these triggers to automate your workflow:");
    lines.push("");
    for (const hook of latentHooks) {
      const patternDesc = hook.pattern ? ` (for \`${hook.pattern}\`)` : "";
      lines.push(`- **${hook.event}**: \`${hook.command}\`${patternDesc}`);
    }
    lines.push("");
  }

  return lines.join("\n");
}
