/**
 * .clinerules Generator
 *
 * Generates rules file for Cline (formerly Claude Dev) and Roo Code.
 * File location: .clinerules at project root.
 *
 * @module formats/cline-rules
 */

import type { ScanResult } from "../types.js";

export function generateClineRules(scan: ScanResult, customRules: string[] = []): string {
  const { components, framework, hooks, utilities, commands, apiRoutes, patterns, database, barrels, stats } = scan;
  const lines: string[] = [];

  lines.push("# Project Rules for Cline");
  lines.push("");
  lines.push(`<!-- Auto-generated by hashmark (https://hashmark.md) -->`);
  lines.push("");

  // Project overview
  const stack: string[] = [];
  if (framework.name !== "Unknown") stack.push(framework.version ? `${framework.name} ${framework.version}` : framework.name);
  if (framework.router) stack.push(framework.router);
  if (framework.language === "TypeScript") stack.push("TypeScript");
  if (framework.styling) stack.push(framework.styling);
  if (utilities.hasShadcn) stack.push("shadcn/ui");
  if (database) stack.push(`${database.provider}`);
  lines.push(`## Stack: ${stack.join(" + ")}`);
  if (stats) lines.push(`${stats.totalFiles} files, ${components.length} components`);
  lines.push("");

  // Critical rules — Cline responds well to numbered directives
  lines.push("## Rules");
  lines.push("");
  let n = 1;
  if (components.length > 0) {
    lines.push(`${n}. ALWAYS use existing components (${components.length} available). NEVER create duplicates.`);
    n++;
  }
  lines.push(`${n}. ALWAYS use semantic design tokens: bg-primary, text-foreground, border-border.`);
  n++;
  lines.push(`${n}. NEVER hardcode color values (no bg-blue-500, no #hex, no rgb()).`);
  n++;
  if (utilities.hasCn) {
    lines.push(`${n}. Use cn() from "${utilities.cnPath}" for conditional classes.`);
    n++;
  }
  if (utilities.hasMode) {
    lines.push(`${n}. Use mode from "${utilities.modePath}" for theme-aware styling.`);
    n++;
  }
  if (framework.name === "Next.js" && framework.router === "App Router") {
    lines.push(`${n}. Default to Server Components. Only add 'use client' for interactivity.`);
    n++;
    lines.push(`${n}. Use next/image for images and next/link for navigation.`);
    n++;
  }
  if (framework.language === "TypeScript") {
    lines.push(`${n}. Type all function parameters. NEVER use 'any'.`);
    n++;
  }
  if (framework.styling === "Tailwind CSS") {
    lines.push(`${n}. Use Tailwind scale values. No arbitrary values like w-[137px].`);
    n++;
  }
  for (const rule of customRules) {
    lines.push(`${n}. ${rule}`);
    n++;
  }
  lines.push("");

  // Commands
  lines.push("## Commands");
  lines.push("");
  if (commands.dev) lines.push(`- npm run dev — Start development server`);
  if (commands.build) lines.push(`- npm run build — Production build`);
  if (commands.test) lines.push(`- npm test — Run tests`);
  if (commands.lint) lines.push(`- npm run lint — Lint code`);
  if (commands.typecheck) lines.push(`- npm run typecheck — Type check`);
  if (commands.db) {
    for (const [name] of Object.entries(commands.db)) {
      lines.push(`- npm run ${name} — Database`);
    }
  }
  lines.push("");

  // Components
  if (components.length > 0) {
    lines.push("## Components");
    lines.push("");

    const grouped: Record<string, typeof components> = {};
    for (const comp of components) {
      const parts = comp.path.split("/");
      parts.pop();
      const dir = parts.pop() || "root";
      if (!grouped[dir]) grouped[dir] = [];
      grouped[dir].push(comp);
    }

    for (const [dir, comps] of Object.entries(grouped)) {
      lines.push(`### ${dir}`);
      for (const comp of comps) {
        const propsStr = comp.props && comp.props.length > 0
          ? ` (${comp.props.slice(0, 4).join(", ")})`
          : "";
        lines.push(`- ${comp.name}${propsStr} — ${comp.importPath}`);
      }
      lines.push("");
    }
  }

  // Hooks
  if (hooks.length > 0) {
    lines.push("## Hooks");
    lines.push("");
    for (const hook of hooks) {
      lines.push(`- ${hook.name} — ${hook.importPath}`);
    }
    lines.push("");
  }

  // API Routes
  if (apiRoutes.length > 0) {
    lines.push("## API Routes");
    lines.push("");
    for (const route of apiRoutes.slice(0, 15)) {
      lines.push(`- ${route.methods.join(",")} ${route.path}${route.isProtected ? " [auth required]" : ""}`);
    }
    lines.push("");
  }

  // Database
  if (database && database.models.length > 0) {
    lines.push("## Database Models");
    lines.push("");
    for (const model of database.models.slice(0, 15)) {
      lines.push(`**${model.name}**: ${model.fields.join(", ")}`);
      if (model.relations.length > 0) {
        lines.push(`  Relations: ${model.relations.join(", ")}`);
      }
    }
    lines.push("");
  }

  // Patterns
  if (patterns.patterns.length > 0) {
    lines.push("## Patterns");
    lines.push("");
    for (const pattern of patterns.patterns) {
      lines.push(`- ${pattern}`);
    }
    lines.push("");
  }

  return lines.join("\n");
}
