/**
 * .github/copilot-instructions.md Generator
 *
 * Generates custom instructions for GitHub Copilot.
 * File location: .github/copilot-instructions.md
 *
 * Copilot reads this file for project-specific coding guidelines.
 *
 * @module formats/copilot-md
 */

import type { ScanResult } from "../types.js";

export function generateCopilotMd(scan: ScanResult, customRules: string[] = []): string {
  const { components, framework, hooks, utilities, commands, apiRoutes, patterns, database, barrels, variants } = scan;
  const lines: string[] = [];

  lines.push("# Copilot Instructions");
  lines.push("");
  lines.push(`<!-- Auto-generated by hashmark (https://hashmark.md) -->`);
  lines.push("");

  // Project overview
  lines.push("## Project Overview");
  lines.push("");
  const stack: string[] = [];
  if (framework.name !== "Unknown") stack.push(framework.version ? `${framework.name} ${framework.version}` : framework.name);
  if (framework.router) stack.push(framework.router);
  if (framework.language === "TypeScript") stack.push("TypeScript");
  if (framework.styling) stack.push(framework.styling);
  if (utilities.hasShadcn) stack.push("shadcn/ui");
  lines.push(`This is a ${stack.join(" + ")} project with ${components.length} components.`);
  lines.push("");

  // Coding standards
  lines.push("## Coding Standards");
  lines.push("");

  if (components.length > 0) {
    lines.push(`- This project has ${components.length} existing components. Always reuse them instead of creating new ones.`);
  }
  lines.push("- Use semantic design tokens for colors (e.g., `bg-primary`, `text-foreground`). Never hardcode color values.");
  if (utilities.hasCn) {
    lines.push(`- Use the \`cn()\` utility from \`${utilities.cnPath}\` for merging CSS classes conditionally.`);
  }
  if (utilities.hasMode) {
    lines.push(`- Use the \`mode\` object from \`${utilities.modePath}\` for theme-aware styling.`);
  }
  if (framework.name === "Next.js" && framework.router === "App Router") {
    lines.push("- Use Server Components by default. Only use `'use client'` directive for interactive components.");
    lines.push("- Use `next/image` for optimized images and `next/link` for client-side navigation.");
  }
  if (framework.language === "TypeScript") {
    lines.push("- Always provide explicit types for function parameters and return values.");
    lines.push("- Never use `any` type. Use `unknown` when the type is truly unknown.");
  }
  if (framework.styling === "Tailwind CSS") {
    lines.push("- Use Tailwind CSS utility classes. Avoid arbitrary values like `w-[137px]`.");
  }

  for (const rule of customRules) {
    lines.push(`- ${rule}`);
  }
  lines.push("");

  // Component library
  if (components.length > 0) {
    lines.push("## Component Library");
    lines.push("");
    lines.push("When generating UI code, use these existing components:");
    lines.push("");

    const grouped: Record<string, string[]> = {};
    for (const comp of components) {
      const parts = comp.path.split("/");
      parts.pop();
      const dir = parts.pop() || "root";
      if (!grouped[dir]) grouped[dir] = [];
      grouped[dir].push(comp.name);
    }

    for (const [dir, names] of Object.entries(grouped)) {
      lines.push(`**${dir}**: ${names.join(", ")}`);
    }
    lines.push("");

    // Import examples
    if (barrels.length > 0) {
      lines.push("### Import Patterns");
      lines.push("");
      lines.push("```typescript");
      for (const barrel of barrels.slice(0, 3)) {
        const exports = barrel.exports.filter(e => !e.startsWith("*")).slice(0, 3).join(", ");
        if (exports) lines.push(`import { ${exports} } from "${barrel.importPath}";`);
      }
      lines.push("```");
      lines.push("");
    }
  }

  // Custom hooks
  if (hooks.length > 0) {
    lines.push("## Custom Hooks");
    lines.push("");
    for (const hook of hooks) {
      lines.push(`- \`${hook.name}\` from \`${hook.importPath}\``);
    }
    lines.push("");
  }

  // API conventions
  if (apiRoutes.length > 0) {
    lines.push("## API Routes");
    lines.push("");
    for (const route of apiRoutes.slice(0, 15)) {
      lines.push(`- \`${route.methods.join(", ")}\` \`${route.path}\`${route.isProtected ? " (authenticated)" : ""}`);
    }
    lines.push("");
  }

  // Database
  if (database && database.models.length > 0) {
    lines.push("## Database Models");
    lines.push("");
    lines.push(`Using ${database.provider} with ${database.models.length} models:`);
    lines.push("");
    for (const model of database.models.slice(0, 10)) {
      lines.push(`- **${model.name}**: ${model.fields.slice(0, 5).join(", ")}`);
    }
    lines.push("");
  }

  // Patterns
  if (patterns.patterns.length > 0) {
    lines.push("## Detected Patterns");
    lines.push("");
    for (const pattern of patterns.patterns) {
      lines.push(`- ${pattern}`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("*Generated by [hashmark](https://hashmark.md)*");
  lines.push("");

  return lines.join("\n");
}
