/**
 * .cursorrules Generator
 *
 * Generates the legacy single-file .cursorrules for Cursor AI.
 * This is a plain text/markdown file at the project root.
 *
 * @module formats/cursor-rules
 */

import type { ScanResult } from "../types.js";

export function generateCursorRules(scan: ScanResult, customRules: string[] = []): string {
  const { components, framework, hooks, utilities, commands, apiRoutes, patterns, database, stats, variants, barrels } = scan;
  const lines: string[] = [];

  lines.push("# Project Rules");
  lines.push("");
  lines.push(`> Auto-generated by hashmark (https://hashmark.md)`);
  lines.push("");

  // Project context
  lines.push("## Project");
  lines.push("");
  const stack: string[] = [];
  if (framework.name !== "Unknown") stack.push(framework.version ? `${framework.name} ${framework.version}` : framework.name);
  if (framework.router) stack.push(framework.router);
  if (framework.language === "TypeScript") stack.push("TypeScript");
  if (framework.styling) stack.push(framework.styling);
  if (utilities.hasShadcn) stack.push("shadcn/ui");
  if (database) stack.push(`${database.provider}`);
  lines.push(`Stack: ${stack.join(", ")}`);
  if (stats) lines.push(`Codebase: ${stats.totalFiles} files, ${components.length} components`);
  lines.push("");

  // Rules
  lines.push("## Rules");
  lines.push("");
  if (components.length > 0) {
    lines.push(`- Always use existing components (${components.length} available). Never create duplicates.`);
  }
  lines.push("- Use semantic design tokens (bg-primary, text-foreground) — never hardcode colors.");
  if (utilities.hasCn) {
    lines.push(`- Use cn() from "${utilities.cnPath}" for conditional CSS classes.`);
  }
  if (utilities.hasMode) {
    lines.push(`- Use mode object from "${utilities.modePath}" for theme-aware styling.`);
  }
  if (framework.name === "Next.js" && framework.router === "App Router") {
    lines.push("- Default to Server Components. Only add 'use client' when interactivity is needed.");
    lines.push("- Use next/image for images and next/link for navigation.");
  }
  if (framework.language === "TypeScript") {
    lines.push("- Type all function parameters and return types. Never use 'any'.");
  }
  if (framework.styling === "Tailwind CSS") {
    lines.push("- Use Tailwind scale values. Avoid arbitrary values like w-[137px].");
  }

  for (const rule of customRules) {
    lines.push(`- ${rule}`);
  }
  lines.push("");

  // Components
  if (components.length > 0) {
    lines.push("## Components");
    lines.push("");
    lines.push("Available components — use these instead of creating new ones:");
    lines.push("");

    const grouped: Record<string, string[]> = {};
    for (const comp of components) {
      const parts = comp.path.split("/");
      parts.pop();
      const dir = parts.pop() || "root";
      if (!grouped[dir]) grouped[dir] = [];
      grouped[dir].push(comp.name);
    }

    for (const [dir, names] of Object.entries(grouped)) {
      lines.push(`${dir}: ${names.join(", ")}`);
    }
    lines.push("");
  }

  // Key imports
  if (barrels.length > 0 || utilities.hasCn || utilities.hasMode) {
    lines.push("## Imports");
    lines.push("");
    if (utilities.hasCn) lines.push(`cn() → "${utilities.cnPath}"`);
    if (utilities.hasMode) lines.push(`mode → "${utilities.modePath}"`);
    for (const barrel of barrels.slice(0, 5)) {
      const exports = barrel.exports.filter(e => !e.startsWith("*")).slice(0, 4).join(", ");
      if (exports) lines.push(`{ ${exports} } → "${barrel.importPath}"`);
    }
    lines.push("");
  }

  // Hooks
  if (hooks.length > 0) {
    lines.push("## Hooks");
    lines.push("");
    for (const hook of hooks) {
      lines.push(`${hook.name} → "${hook.importPath}"${hook.isClientOnly ? " (client only)" : ""}`);
    }
    lines.push("");
  }

  // API Routes
  if (apiRoutes.length > 0) {
    lines.push("## API");
    lines.push("");
    for (const route of apiRoutes.slice(0, 15)) {
      const methods = route.methods.join(",");
      lines.push(`${methods} ${route.path}${route.isProtected ? " (auth)" : ""}`);
    }
    lines.push("");
  }

  // Database
  if (database && database.models.length > 0) {
    lines.push("## Database");
    lines.push("");
    for (const model of database.models.slice(0, 15)) {
      lines.push(`${model.name}: ${model.fields.slice(0, 5).join(", ")}`);
    }
    lines.push("");
  }

  // Patterns
  if (patterns.patterns.length > 0) {
    lines.push("## Patterns");
    lines.push("");
    for (const pattern of patterns.patterns) {
      lines.push(`- ${pattern}`);
    }
    lines.push("");
  }

  // Commands
  lines.push("## Commands");
  lines.push("");
  if (commands.dev) lines.push(`dev: npm run dev`);
  if (commands.build) lines.push(`build: npm run build`);
  if (commands.test) lines.push(`test: npm test`);
  if (commands.lint) lines.push(`lint: npm run lint`);
  lines.push("");

  return lines.join("\n");
}
