/**
 * GEMINI.md Generator
 *
 * Generates context file for Google Gemini CLI.
 * File location: GEMINI.md at project root.
 *
 * @module formats/gemini-md
 */

import type { ScanResult } from "../types.js";

export function generateGeminiMd(scan: ScanResult, customRules: string[] = []): string {
  const { components, framework, hooks, utilities, commands, apiRoutes, patterns, database, stats, barrels, envVars } = scan;
  const lines: string[] = [];

  lines.push("# GEMINI.md");
  lines.push("");
  lines.push(`> Auto-generated by [hashmark](https://hashmark.md) — Context for Google Gemini CLI`);
  lines.push("");

  // Project description
  lines.push("## Project");
  lines.push("");
  const stack: string[] = [];
  if (framework.name !== "Unknown") stack.push(framework.version ? `${framework.name} ${framework.version}` : framework.name);
  if (framework.router) stack.push(framework.router);
  if (framework.language === "TypeScript") stack.push("TypeScript");
  if (framework.styling) stack.push(framework.styling);
  if (utilities.hasShadcn) stack.push("shadcn/ui");
  if (database) stack.push(`${database.provider}`);

  lines.push(`**Stack**: ${stack.join(", ")}`);
  if (stats) {
    lines.push(`**Size**: ${stats.totalFiles} files, ${stats.totalLines.toLocaleString()} lines`);
    lines.push(`**Components**: ${components.length}`);
  }
  lines.push("");

  // Commands
  lines.push("## Commands");
  lines.push("");
  lines.push("```bash");
  if (commands.dev) lines.push(`npm run dev          # Start dev server`);
  if (commands.build) lines.push(`npm run build        # Production build`);
  if (commands.test) lines.push(`npm test             # Run tests`);
  if (commands.lint) lines.push(`npm run lint         # Lint code`);
  if (commands.typecheck) lines.push(`npm run typecheck    # Type check`);
  lines.push("```");
  lines.push("");

  // Rules
  lines.push("## Coding Rules");
  lines.push("");
  if (components.length > 0) {
    lines.push(`- Use existing ${components.length} components. Don't create duplicates.`);
  }
  lines.push("- Use semantic design tokens: `bg-primary`, `text-foreground`, `border-border`.");
  lines.push("- Never hardcode color values.");
  if (utilities.hasCn) {
    lines.push(`- Use \`cn()\` from \`${utilities.cnPath}\` for conditional CSS classes.`);
  }
  if (utilities.hasMode) {
    lines.push(`- Use \`mode\` from \`${utilities.modePath}\` for theme-aware styling.`);
  }
  if (framework.name === "Next.js" && framework.router === "App Router") {
    lines.push("- Default to Server Components. Add `'use client'` only for interactivity.");
    lines.push("- Use `next/image` and `next/link`.");
  }
  if (framework.language === "TypeScript") {
    lines.push("- Type all parameters. Avoid `any`.");
  }

  for (const rule of customRules) {
    lines.push(`- ${rule}`);
  }
  lines.push("");

  // Architecture
  lines.push("## Architecture");
  lines.push("");

  // Components
  if (components.length > 0) {
    lines.push("### Components");
    lines.push("");
    const grouped: Record<string, string[]> = {};
    for (const comp of components) {
      const parts = comp.path.split("/");
      parts.pop();
      const dir = parts.pop() || "root";
      if (!grouped[dir]) grouped[dir] = [];
      grouped[dir].push(comp.name);
    }
    for (const [dir, names] of Object.entries(grouped)) {
      lines.push(`- **${dir}**: ${names.join(", ")}`);
    }
    lines.push("");
  }

  // Key imports
  if (barrels.length > 0 || utilities.hasCn) {
    lines.push("### Key Imports");
    lines.push("");
    lines.push("```typescript");
    if (utilities.hasCn) lines.push(`import { cn } from "${utilities.cnPath}";`);
    if (utilities.hasMode) lines.push(`import { mode } from "${utilities.modePath}";`);
    for (const barrel of barrels.slice(0, 3)) {
      const exports = barrel.exports.filter(e => !e.startsWith("*")).slice(0, 3).join(", ");
      if (exports) lines.push(`import { ${exports} } from "${barrel.importPath}";`);
    }
    lines.push("```");
    lines.push("");
  }

  // Hooks
  if (hooks.length > 0) {
    lines.push("### Hooks");
    lines.push("");
    for (const hook of hooks) {
      lines.push(`- \`${hook.name}\` — \`${hook.importPath}\`${hook.isClientOnly ? " (client only)" : ""}`);
    }
    lines.push("");
  }

  // API
  if (apiRoutes.length > 0) {
    lines.push("### API Routes");
    lines.push("");
    for (const route of apiRoutes.slice(0, 15)) {
      const methods = route.methods.join(", ");
      lines.push(`- \`${methods}\` \`${route.path}\`${route.isProtected ? " (auth)" : ""}`);
    }
    lines.push("");
  }

  // Database
  if (database && database.models.length > 0) {
    lines.push("### Database");
    lines.push("");
    lines.push(`${database.provider} with ${database.models.length} models:`);
    lines.push("");
    for (const model of database.models.slice(0, 15)) {
      lines.push(`- **${model.name}**: ${model.fields.slice(0, 5).join(", ")}`);
      if (model.relations.length > 0) {
        lines.push(`  Relations: ${model.relations.join(", ")}`);
      }
    }
    lines.push("");
  }

  // Env vars
  if (envVars.length > 0) {
    const required = envVars.filter(e => e.required);
    if (required.length > 0) {
      lines.push("### Environment Variables");
      lines.push("");
      for (const env of required.slice(0, 10)) {
        lines.push(`- \`${env.name}\` (required)`);
      }
      lines.push("");
    }
  }

  // Patterns
  if (patterns.patterns.length > 0) {
    lines.push("### Patterns");
    lines.push("");
    for (const pattern of patterns.patterns) {
      lines.push(`- ${pattern}`);
    }
    lines.push("");
  }

  return lines.join("\n");
}
