/**
 * .windsurfrules Generator
 *
 * Generates rules file for Windsurf (Codeium) AI coding assistant.
 * File location: .windsurfrules at project root.
 *
 * @module formats/windsurf-rules
 */

import type { ScanResult } from "../types.js";

export function generateWindsurfRules(scan: ScanResult, customRules: string[] = []): string {
  const { components, framework, hooks, utilities, commands, apiRoutes, patterns, database, barrels } = scan;
  const lines: string[] = [];

  lines.push("# Windsurf Rules");
  lines.push("");
  lines.push(`# Auto-generated by hashmark (https://hashmark.md)`);
  lines.push("");

  // Project context
  const stack: string[] = [];
  if (framework.name !== "Unknown") stack.push(framework.version ? `${framework.name} ${framework.version}` : framework.name);
  if (framework.language === "TypeScript") stack.push("TypeScript");
  if (framework.styling) stack.push(framework.styling);
  if (utilities.hasShadcn) stack.push("shadcn/ui");
  lines.push(`## Project: ${stack.join(" + ")}`);
  lines.push("");

  // Rules
  lines.push("## Coding Rules");
  lines.push("");
  if (components.length > 0) {
    lines.push(`1. Use existing components (${components.length} available). Never create duplicates.`);
  }
  lines.push(`${components.length > 0 ? "2" : "1"}. Use semantic design tokens (bg-primary, text-foreground). No hardcoded colors.`);
  let ruleNum = components.length > 0 ? 3 : 2;
  if (utilities.hasCn) {
    lines.push(`${ruleNum}. Use cn() from "${utilities.cnPath}" for conditional classes.`);
    ruleNum++;
  }
  if (utilities.hasMode) {
    lines.push(`${ruleNum}. Use mode from "${utilities.modePath}" for theming.`);
    ruleNum++;
  }
  if (framework.name === "Next.js" && framework.router === "App Router") {
    lines.push(`${ruleNum}. Default to Server Components. Use 'use client' only when needed.`);
    ruleNum++;
  }
  if (framework.language === "TypeScript") {
    lines.push(`${ruleNum}. Type all parameters. Never use 'any'.`);
    ruleNum++;
  }
  for (const rule of customRules) {
    lines.push(`${ruleNum}. ${rule}`);
    ruleNum++;
  }
  lines.push("");

  // Components
  if (components.length > 0) {
    lines.push("## Components");
    lines.push("");

    const grouped: Record<string, string[]> = {};
    for (const comp of components) {
      const parts = comp.path.split("/");
      parts.pop();
      const dir = parts.pop() || "root";
      if (!grouped[dir]) grouped[dir] = [];
      grouped[dir].push(comp.name);
    }

    for (const [dir, names] of Object.entries(grouped)) {
      lines.push(`${dir}: ${names.join(", ")}`);
    }
    lines.push("");
  }

  // Key imports
  if (barrels.length > 0) {
    lines.push("## Import Paths");
    lines.push("");
    if (utilities.hasCn) lines.push(`- cn(): "${utilities.cnPath}"`);
    if (utilities.hasMode) lines.push(`- mode: "${utilities.modePath}"`);
    for (const barrel of barrels.slice(0, 5)) {
      const exports = barrel.exports.filter(e => !e.startsWith("*")).slice(0, 3).join(", ");
      if (exports) lines.push(`- { ${exports} }: "${barrel.importPath}"`);
    }
    lines.push("");
  }

  // Hooks
  if (hooks.length > 0) {
    lines.push("## Hooks");
    lines.push("");
    for (const hook of hooks) {
      lines.push(`- ${hook.name} from "${hook.importPath}"`);
    }
    lines.push("");
  }

  // API
  if (apiRoutes.length > 0) {
    lines.push("## API Routes");
    lines.push("");
    for (const route of apiRoutes.slice(0, 15)) {
      lines.push(`${route.methods.join(",")} ${route.path}${route.isProtected ? " [auth]" : ""}`);
    }
    lines.push("");
  }

  // Database
  if (database && database.models.length > 0) {
    lines.push("## Database");
    lines.push("");
    lines.push(`${database.provider} models:`);
    for (const model of database.models.slice(0, 10)) {
      lines.push(`- ${model.name}: ${model.fields.slice(0, 5).join(", ")}`);
    }
    lines.push("");
  }

  // Commands
  lines.push("## Commands");
  lines.push("");
  if (commands.dev) lines.push(`dev: npm run dev`);
  if (commands.build) lines.push(`build: npm run build`);
  if (commands.test) lines.push(`test: npm test`);
  if (commands.lint) lines.push(`lint: npm run lint`);
  lines.push("");

  lines.push("---");
  lines.push("*Generated by [hashmark](https://hashmark.md)*");
  lines.push("");

  return lines.join("\n");
}
